### ISSUE TITLE
Visualizations Fail to Load after Renaming Pipeline 

### ISSUE THREAD

**Issue by d3rpd3rp** [tensorflow/tfx#3603] opened 2021-04-22 15:02 UTC
**Describe the current behavior**

Renaming the pipeline from the notebook in the first cell of Step 2 from "my-pipeline" to "my_pipeline" prohibits components visualization (like StatisticsGen) to load in the UI.

**Describe the expected behavior**

Visualization components load after renaming pipeline to "my_pipeline".

**Standalone code to reproduce the issue**

Using the notebook https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/template.ipynb

Modify name in Step 2, cell one, from 
PIPELINE_NAME="my_pipeline"
to
PIPELINE_NAME="my-pipeline"

then, in Step 5, follow the instructions to uncomment StatisticsGen and SchemaGen:

Double-click to change directory to pipeline and double-click again to open pipeline.py. Find and uncomment the 3 lines which add StatisticsGen, SchemaGen, and ExampleValidator to the pipeline. (Tip: search for comments containing TODO(step 5):). Make sure to save pipeline.py after you edit it.

Then attempt to view the "Visualizations" tab in the Kubeflow UI.

**Comment by gaikwadrahul8** [comment] 2022-11-30 09:46
@d3rpd3rp 

Apologies for the delayed response and We have updated that official documentation so I would request you to please try to follow all the instructions mentioned in this [file](https://github.com/tensorflow/tfx/blob/master/docs/tutorials/tfx/template.ipynb) and even I have attached one good resource with ML Models in Production Using TensorFlow Extended (TFX) and Kubeflow [here](https://neptune.ai/blog/deep-dive-into-ml-models-in-production-using-tfx-and-kubeflow) for your reference and I hope it will help you to resolve your issue and if issue still persists please let us know and if possible please help us with error log to do investigation to find root cause of your issue ?

Thank you!

**Comment by gaikwadrahul8** [comment] 2022-12-27 08:23
Hi, @d3rpd3rp 

It seems like there some versions compatibility between TFX and Kubeflow so I would recommend you to please go with versions mentioned in this [Kubeflow Pipelines compatibility matrix with TensorFlow Extended (TFX)
](https://www.kubeflow.org/docs/components/pipelines/v1/installation/compatibility-matrix/)

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue, if you need any further assistance or update

Thank you!

**Closed** 2022-12-27 08:23 UTC
Labels: type:bug, stat:awaiting response
