### ISSUE TITLE
Running CSVExampleGen on Windows With Input_Config >> ERROR

### ISSUE THREAD

**Issue by wlee192** [tensorflow/tfx#3317] opened 2021-03-03 04:58 UTC
**System information** - Have I specified the code to reproduce the issue
(Yes/No): Yes
Environment in which the code is executed (e.g., Local
(Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc): Local Windows 10 
TensorFlow version (you are using): 2.4.1
TFX Version: 0.27.0
Python version: 3.6.8

**Describe the current behavior**

Running on Colab was fine. 
When i tried to then run the same on my Windows 10 Machine, an error has come up for the CSVExampleGen Component.

See below for the error message and what i was trying to achieve

**Describe the expected behavior**

**CSVExampleGen Config**

```
  custom_split = example_gen_pb2.Output(
    split_config=example_gen_pb2.SplitConfig(splits=[
      example_gen_pb2.SplitConfig.Split(name ='train', hash_buckets = 60),
      example_gen_pb2.SplitConfig.Split(name ='test', hash_buckets = 10),
      example_gen_pb2.SplitConfig.Split(name ='eval', hash_buckets = 20)
    ]))

  input_config = example_gen_pb2.Input(splits=[
    example_gen_pb2.Input.Split(name ='train', 
                                pattern ='span-{SPAN}/*')
    ])


  example_gen = CsvExampleGen(input_base = data_root, input_config = input_config, output_config = custom_split)
```

The folder which contains the CSVs is simply named as **span-1**

When i run it on my local windows machine, the error message below comes up - which from the looks of it, is complaining about the `pattern `field in the `input_config `above.

Is this not supported on a windows machine? it works on Colab without any issue

```
c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\local\local_dag_runner.py in run(self, tfx_pipeline)
     90             component_config=component_config)
     91         logging.info('Component %s is running.', component.id)
---> 92         component_launcher.launch()
     93         logging.info('Component %s is finished.', component.id)

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\launcher\base_component_launcher.py in launch(self)
    196                       self._component_info.component_id)
    197     execution_decision = self._run_driver(self._input_dict, self._output_dict,
--> 198                                           self._exec_properties)
    199 
    200     if not execution_decision.use_cached_results:

c:\SentinelMlTfLocal\lib\site-packages\tfx\orchestration\launcher\base_component_launcher.py in _run_driver(self, input_dict, output_dict, exec_properties)
    165           driver_args=self._driver_args,
    166           pipeline_info=self._pipeline_info,
--> 167           component_info=self._component_info)
    168 
    169       return execution_decision

c:\SentinelMlTfLocal\lib\site-packages\tfx\dsl\components\base\base_driver.py in pre_execution(self, input_dict, output_dict, exec_properties, driver_args, pipeline_info, component_info)
    266     exec_properties = self.resolve_exec_properties(exec_properties,
    267                                                    pipeline_info,
--> 268                                                    component_info)
    269     input_artifacts = self.resolve_input_artifacts(input_dict, exec_properties,
    270                                                    driver_args, pipeline_info)

c:\SentinelMlTfLocal\lib\site-packages\tfx\components\example_gen\driver.py in resolve_exec_properties(***failed resolving arguments***)
    110     # Note that this function updates the input_config.splits.pattern.
    111     fingerprint, span, version = utils.calculate_splits_fingerprint_span_and_version(
--> 112         input_base, input_config.splits, range_config)
    113 
    114     exec_properties[utils.INPUT_CONFIG_KEY] = proto_utils.proto_to_json(

c:\SentinelMlTfLocal\lib\site-packages\tfx\components\example_gen\utils.py in calculate_splits_fingerprint_span_and_version(input_base_uri, splits, range_config)
    632     # Find most recent span and version for this split.
    633     target_span, target_version = _get_target_span_version(
--> 634         input_base_uri, split, range_config=range_config)
    635 
    636     # TODO(b/162622803): add default behavior for when version spec not present.

c:\SentinelMlTfLocal\lib\site-packages\tfx\components\example_gen\utils.py in _get_target_span_version(uri, split, range_config)
    562         _find_matched_span_version_from_path(file_path, split_regex_pattern,
    563                                              is_match_span, is_match_date,
--> 564                                              is_match_version))
    565 
    566     if latest_span_int is None or match_span_int > latest_span_int:

c:\SentinelMlTfLocal\lib\site-packages\tfx\components\example_gen\utils.py in _find_matched_span_version_from_path(file_path, split_regex_pattern, is_match_span, is_match_date, is_match_version)
    299   result = re.search(split_regex_pattern, file_path)
    300   if result is None:
--> 301     raise ValueError('Glob pattern does not match regex pattern')
    302 
    303   matched_span_tokens = None

ValueError: Glob pattern does not match regex pattern
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by arghyaganguly** [comment] 2021-03-03 09:46
@wlee192, I tried reproducing this in linux but the error doesn't exist.
Feels like this is not supported in windows.

**Comment by wlee192** [comment] 2021-03-04 01:15
Hi @arghyaganguly ,

Thanks for the quick test, that's what i thought would be the case as well. 
Do you know if this is more of a bug or will be more of a feature request?

I really like the capability of the `input_config `of the CSVExampleGen where one could version the input training files, but at this stage i'll have to implement my own logic since i'm using it on Windows machine.

**Comment by 1025KB** [comment] 2021-03-04 01:20
It might because of glob/regex pattern difference on window, you can try print the glob regex pattern [here](https://source.corp.google.com/piper///depot/google3/third_party/py/tfx/components/example_gen/utils.py;l=229)

and see if that glob pattern can glob files on windows

**Comment by wlee192** [comment] 2021-03-05 01:21
@1025KB yea the glob doesn't work on windows, and as you suggested, at this stage will have to implement window specific logic. 
@arghyaganguly shall i leave this issue open at this stage (in case this makes it to future feature release?) or close it out since it's not currently supported?

**Comment by arghyaganguly** [comment] 2021-03-05 02:44
@wlee192 ,it will help if you can share your workaround for others who might encounter the same while using windows.
Currently i am keeping this open with the possibility that it is addressed in future releases.
Thanks.

**Comment by arghyaganguly** [comment] 2021-04-15 10:51
Closing this based on above comments.Thanks.

**Closed by arghyaganguly** 2021-04-15 10:51 UTC
Labels: type:bug

**Comment by avelez93** [comment] 2022-02-21 13:28
Hello,
I am running example_gen library in windows. 
As you mentioned in this post I have implemented window specific logic. However I still have some problemes.

First I add my below:

_data_root = os.path.join('data_csv','Prueba_Span','')
inputs = proto.Input(splits=[
                example_gen_pb2.Input.Split(pattern='data_{SPAN}\\*')])
example_gen = CsvExampleGen(input_base=_data_root,input_config=inputs)
context.run(example_gen)

This is the Error:

  File "**.py", line 136, in <module>
    context.run(example_gen)
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\orchestration\experimental\interactive\interactive_context.py", line 63, in run_if_ipython
    return fn(*args, **kwargs)
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\orchestration\experimental\interactive\interactive_context.py", line 183, in run
    execution_id = launcher.launch().execution_id
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\orchestration\launcher\base_component_launcher.py", line 191, in launch
    execution_decision = self._run_driver(self._input_dict, self._output_dict,
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\orchestration\launcher\base_component_launcher.py", line 155, in _run_driver
    execution_decision = driver.pre_execution(
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\dsl\components\base\base_driver.py", line 269, in pre_execution
    exec_properties = self.resolve_exec_properties(exec_properties,
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\components\example_gen\driver.py", line 109, in resolve_exec_properties
    span, version = processor.resolve_span_and_version()
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\components\example_gen\input_processor.py", line 166, in resolve_span_and_version
    self._fingerprint, span, version = utils.calculate_splits_fingerprint_span_and_version(
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\components\example_gen\utils.py", line 700, in calculate_splits_fingerprint_span_and_version
    target_span, target_version = _get_target_span_version(
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\components\example_gen\utils.py", line 629, in _get_target_span_version
    _find_matched_span_version_from_path(file_path, split_regex_pattern,
  File ".\Anaconda3\envs\tfx\lib\site-packages\tfx\components\example_gen\utils.py", line 367, in _find_matched_span_version_from_path
    result = re.search(split_regex_pattern, file_path)
  File ".\Anaconda3\envs\tfx\lib\re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File ".\Anaconda3\envs\tfx\lib\re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File ".\Anaconda3\envs\tfx\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File ".\Anaconda3\envs\tfx\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File ".\Anaconda3\envs\tfx\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File ".\Anaconda3\envs\tfx\lib\sre_parse.py", line 525, in _parse
    code = _escape(source, this, state)
  File ".\Anaconda3\envs\tfx\lib\sre_parse.py", line 426, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
error: bad escape \P


As I have shown, the problem is related with the Regular expression syntax. 
I need to define te root path as: 'data_csv\\\\Prueba_Span\\\\'  instead of  'data_csv\\Prueba_Span\\'
The problem is that is I define the path like this, on the library utils when it taques the files with   "files =fileio.glob(split_glob_pattern)" line 626 it gives me an error because split_glob_pattern is defined as 'data_csv\\\\Prueba_Span\\\\data_*\\\\*'

Did anyone have the same problem?

Thanks in advance
