### ISSUE TITLE
TFX example  run exception：TypeError: Receiver() takes no arguments

### ISSUE THREAD

**Issue by dylanwwang** [tensorflow/tfx#2078] opened 2020-06-30 05:41 UTC
Python 3.7.3 
apache-beam  2.17.0 
tensorflow  1.15.0 
tfx  0.21.3
------------------------------------- exception info：
I0630 13:37:23.116711  2404 fn_api_runner.py:672] Running (((((ref_AppliedPTransform_CreateRoot/Read_3)+(ref_AppliedPTransform_Run[CsvExampleGen]_4))+(ref_AppliedPTransform_Run[ResolverNode.latest_blessed_model_resolver]_5))+(ref_PCollection_PCollection_1/Write))+(ref_PCollection_PCollection_2/Write))+(ref_PCollection_PCollection_3/Write)
Traceback (most recent call last):
  File "D:/project/Python/TFXTest/examples/iris/iris_pipeline_beam.py", line 181, in <module>
    direct_num_workers=0))
  File "D:\Program Files\Anaconda3\lib\site-packages\tfx\orchestration\beam\beam_dag_runner.py", line 154, in run
    absl.logging.info('Component %s is scheduled.', component_id)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\pipeline.py", line 426, in __exit__
    self.run().wait_until_finish()
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\pipeline.py", line 406, in run
    self._options).run(False)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\pipeline.py", line 419, in run
    return self.runner.run_pipeline(self, self._options)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\direct\direct_runner.py", line 132, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py", line 381, in run_pipeline
    default_environment=self._default_environment))
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py", line 388, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py", line 470, in run_stages
    stage_context.safe_coders)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py", line 753, in _run_stage
    result, splits = bundle_manager.process_bundle(data_input, data_output)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py", line 1801, in process_bundle
    part, expected_outputs), part_inputs):
  File "D:\Program Files\Anaconda3\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "D:\Program Files\Anaconda3\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "D:\Program Files\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\Program Files\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py", line 1801, in <lambda>
    part, expected_outputs), part_inputs):
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py", line 1737, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\portability\fn_api_runner.py", line 1150, in push
    response = self.worker.do_instruction(request)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\worker\sdk_worker.py", line 360, in do_instruction
    request.instruction_id)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\worker\sdk_worker.py", line 386, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\worker\bundle_processor.py", line 663, in process_bundle
    data.transform_id].process_encoded(data.data)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\worker\bundle_processor.py", line 143, in process_encoded
    self.output(decoded_value)
  File "D:\Program Files\Anaconda3\lib\site-packages\apache_beam\runners\worker\operations.py", line 256, in output
    cython.cast(Receiver, self.receivers[output_index]).receive(windowed_value)
  File "D:\Program Files\Anaconda3\lib\site-packages\Cython\Shadow.py", line 165, in cast
    return type(*args)
TypeError: Receiver() takes no arguments

**Comment by rmothukuru** [comment] 2020-06-30 06:35
@dylanwwang,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by dylanwwang** [comment] 2020-06-30 06:39
> 
> 
> @dylanwwang,
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

@rmothukuru 
just run this tfx-example in local environment：
https://github.com/tensorflow/tfx/blob/master/tfx/examples/iris/iris_pipeline_beam.py

**Comment by ruoyu90** [comment] 2021-01-25 17:06
This seems to be a env setup issue. Also please make sure the example you run comes from the same version of TFX.  Closing this for now and feel free to reopen if you have further questions.

**Closed by ruoyu90** 2021-01-25 17:06 UTC
Labels: stat:awaiting tensorflower, type:bug
