### ISSUE TITLE
Problems running the pipeline given in tfx tutorials ( https://www.tensorflow.org/tfx/tutorials/tfx/penguin_tfdv )

### ISSUE THREAD

**Issue by pSN0W** [tensorflow/tfx#4993] opened 2022-07-04 06:36 UTC
If the bug is related to a specific library below, please raise an issue in the
respective repo directly:

[TensorFlow Data Validation Repo](https://github.com/tensorflow/data-validation/issues)

[TensorFlow Model Analysis Repo](https://github.com/tensorflow/model-analysis/issues)

[TensorFlow Transform Repo](https://github.com/tensorflow/transform/issues)

[TensorFlow Serving Repo](https://github.com/tensorflow/serving/issues)

**System information**

- Have I specified the code to reproduce the issue (Yes, No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Google Colab
- TensorFlow version: 1.8.0
- TFX Version:2.8.2

**Describe the current behavior**
I tried running the tutorials provided in tfx documentation. The tutorials were working fine few days ago but now I encounter error when I run those pipeline.
When I run the pipeline with tfx 1.8. 0. I get this error : 
```
TypeCheckError: Output type hint violation at WriteStatsOutput[train]: expected <class 'apache_beam.pvalue.PDone'>, got <class 'str'>
```
I though it to be a version bug and downgraded tfx to 1.6.1 and am getting a new error now : 
```
Failed to establish connection to Metadata storage with error: MLMD database version 8 is greater than library version 7.
```
I don't think it's a sytem specific problem because I tried switching my google account and also tried the code on different system but I get the same error.
**Describe the expected behavior**
The pipeline should run and result in the artifacts

**Standalone code to reproduce the issue**
https://colab.research.google.com/github/tensorflow/tfx/blob/master/docs/tutorials/tfx/penguin_tfdv.ipynb

**Other info / logs**
Logs when running it with tfx 1.8.0:
```
pipeline_info=id: "penguin-tfdv-schema"
, pipeline_run_id='2022-07-04T06:25:38.614496')
INFO:absl:Generating statistics for split train.
INFO:absl:MetadataStore with DB connection initialized
ERROR:absl:Execution 4 failed.
INFO:absl:Cleaning up stateless execution info.
---------------------------------------------------------------------------
TypeCheckError                            Traceback (most recent call last)
[<ipython-input-7-b7f8b54eab72>](https://localhost:8080/#) in <module>
      4       pipeline_root=SCHEMA_PIPELINE_ROOT,
      5       data_root=DATA_ROOT,
----> 6       metadata_path=SCHEMA_METADATA_PATH))

12 frames
[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/portable/tfx_runner.py](https://localhost:8080/#) in run(self, pipeline, run_options, **kwargs)
    122     else:
    123       run_options_pb = None
--> 124     return self.run_with_ir(pipeline_pb, run_options=run_options_pb, **kwargs)

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/local/local_dag_runner.py](https://localhost:8080/#) in run_with_ir(self, pipeline, run_options)
    107           with metadata.Metadata(connection_config) as mlmd_handle:
    108             partial_run_utils.snapshot(mlmd_handle, pipeline)
--> 109         component_launcher.launch()
    110         logging.info('Component %s is finished.', node_id)

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/portable/launcher.py](https://localhost:8080/#) in launch(self)
    547               executor_watcher.address)
    548           executor_watcher.start()
--> 549         executor_output = self._run_executor(execution_info)
    550       except Exception as e:  # pylint: disable=broad-except
    551         execution_output = (

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/portable/launcher.py](https://localhost:8080/#) in _run_executor(self, execution_info)
    422     outputs_utils.make_output_dirs(execution_info.output_dict)
    423     try:
--> 424       executor_output = self._executor_operator.run_executor(execution_info)
    425       code = executor_output.execution_result.code
    426       if code != 0:

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/portable/beam_executor_operator.py](https://localhost:8080/#) in run_executor(self, execution_info, make_beam_pipeline_fn)
     96         make_beam_pipeline_fn=make_beam_pipeline_fn)
     97     executor = self._executor_cls(context=context)
---> 98     return python_executor_operator.run_with_executor(execution_info, executor)

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/portable/python_executor_operator.py](https://localhost:8080/#) in run_with_executor(execution_info, executor)
     57   output_dict = copy.deepcopy(execution_info.output_dict)
     58   result = executor.Do(execution_info.input_dict, output_dict,
---> 59                        execution_info.exec_properties)
     60   if not result:
     61     # If result is not returned from the Do function, then try to

[/usr/local/lib/python3.7/dist-packages/tfx/components/statistics_gen/executor.py](https://localhost:8080/#) in Do(self, input_dict, output_dict, exec_properties)
    138             stats_api.GenerateStatistics(stats_options)
    139             | 'WriteStatsOutput[%s]' % split >>
--> 140             stats_api.WriteStatisticsToBinaryFile(output_path))
    141         logging.info('Statistics for split %s written to %s.', split,
    142                      output_uri)

[/usr/local/lib/python3.7/dist-packages/apache_beam/pvalue.py](https://localhost:8080/#) in __or__(self, ptransform)
    135 
    136   def __or__(self, ptransform):
--> 137     return self.pipeline.apply(ptransform, self)
    138 
    139 

[/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py](https://localhost:8080/#) in apply(self, transform, pvalueish, label)
    651     if isinstance(transform, ptransform._NamedPTransform):
    652       return self.apply(
--> 653           transform.transform, pvalueish, label or transform.label)
    654 
    655     if not isinstance(transform, ptransform.PTransform):

[/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py](https://localhost:8080/#) in apply(self, transform, pvalueish, label)
    661       old_label, transform.label = transform.label, label
    662       try:
--> 663         return self.apply(transform, pvalueish)
    664       finally:
    665         transform.label = old_label

[/usr/local/lib/python3.7/dist-packages/apache_beam/pipeline.py](https://localhost:8080/#) in apply(self, transform, pvalueish, label)
    710 
    711       if type_options is not None and type_options.pipeline_type_check:
--> 712         transform.type_check_outputs(pvalueish_result)
    713 
    714       for tag, result in ptransform.get_named_nested_pvalues(pvalueish_result):

[/usr/local/lib/python3.7/dist-packages/apache_beam/transforms/ptransform.py](https://localhost:8080/#) in type_check_outputs(self, pvalueish)
    464 
    465   def type_check_outputs(self, pvalueish):
--> 466     self.type_check_inputs_or_outputs(pvalueish, 'output')
    467 
    468   def type_check_inputs_or_outputs(self, pvalueish, input_or_output):

[/usr/local/lib/python3.7/dist-packages/apache_beam/transforms/ptransform.py](https://localhost:8080/#) in type_check_inputs_or_outputs(self, pvalueish, input_or_output)
    495                 hint=hint,
    496                 actual_type=pvalue_.element_type,
--> 497                 debug_str=type_hints.debug_str()))
    498 
    499   def _infer_output_coder(self, input_type=None, input_coder=None):

TypeCheckError: Output type hint violation at WriteStatsOutput[train]: expected <class 'apache_beam.pvalue.PDone'>, got <class 'str'>
Full type hint:
IOTypeHints[inputs=((<class 'tensorflow_metadata.proto.v0.statistics_pb2.DatasetFeatureStatisticsList'>,), {}), outputs=((<class 'apache_beam.pvalue.PDone'>,), {})]
File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 728, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/local/lib/python3.7/dist-packages/tensorflow_data_validation/api/stats_api.py", line 112, in <module>
    class WriteStatisticsToBinaryFile(beam.PTransform):
File "/usr/local/lib/python3.7/dist-packages/apache_beam/typehints/decorators.py", line 776, in annotate_input_types
    *converted_positional_hints, **converted_keyword_hints)

based on:
  IOTypeHints[inputs=None, outputs=((<class 'apache_beam.pvalue.PDone'>,), {})]
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_data_validation/api/stats_api.py", line 112, in <module>
      class WriteStatisticsToBinaryFile(beam.PTransform):
  File "/usr/local/lib/python3.7/dist-packages/apache_beam/typehints/decorators.py", line 863, in annotate_output_types
      f._type_hints = th.with_output_types(return_type_hint)  # pylint: disable=protected-access
```
With tfx:1.6.1
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-6-b7f8b54eab72>](https://localhost:8080/#) in <module>
      4       pipeline_root=SCHEMA_PIPELINE_ROOT,
      5       data_root=DATA_ROOT,
----> 6       metadata_path=SCHEMA_METADATA_PATH))

4 frames
[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/portable/tfx_runner.py](https://localhost:8080/#) in run(self, pipeline, run_options)
    114     else:
    115       run_options_pb = None
--> 116     return self.run_with_ir(pipeline_pb, run_options=run_options_pb)

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/local/local_dag_runner.py](https://localhost:8080/#) in run_with_ir(self, pipeline, run_options)
    107           with metadata.Metadata(connection_config) as mlmd_handle:
    108             partial_run_utils.snapshot(mlmd_handle, pipeline)
--> 109         component_launcher.launch()
    110         logging.info('Component %s is finished.', node_id)

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/portable/launcher.py](https://localhost:8080/#) in launch(self)
    522 
    523     # Runs as a normal node.
--> 524     execution_preparation_result = self._prepare_execution()
    525     (execution_info, contexts,
    526      is_execution_needed) = (execution_preparation_result.execution_info,

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/portable/launcher.py](https://localhost:8080/#) in _prepare_execution(self)
    252     # Otherwise following retries will keep failing because of duplicate
    253     # publishes.
--> 254     with self._mlmd_connection as m:
    255       # 1.Prepares all contexts.
    256       contexts = context_lib.prepare_contexts(

[/usr/local/lib/python3.7/dist-packages/tfx/orchestration/metadata.py](https://localhost:8080/#) in __enter__(self)
    152     raise RuntimeError(
    153         'Failed to establish connection to Metadata storage with error: %s' %
--> 154         connection_error)
    155 
    156   def __exit__(self, exc_type: Optional[Type[Exception]],

RuntimeError: Failed to establish connection to Metadata storage with error: MLMD database version 8 is greater than library version 7. Please upgrade the library to use the given database in order to prevent potential data loss. If data loss is acceptable, please downgrade the database using a newer version of library.
```

**Comment by nroberts1** [comment] 2022-07-05 14:39
I'm soooo glad to say a work around this hasn't proved very hard to track down. The stack trace heavily pointed towards Apache Beam. Looking at Apache Beam it has a release to 2.40.x a few days ago. I've pinned Apache Beam to 2.39.0 and now this issue has gone away.
Not a fix but should get you running the demo example okay. I think the clue was when I saw your post was yesterday and only with a clean environment did I find the same issue.

**Comment by pSN0W** [comment] 2022-07-05 18:37
Thank You! so much works now.

**Comment by Rupesh-rkgit** [comment] 2022-07-06 05:19
> I have the same issue after running my project in a clean environment so clean Python environment with a pip install - requirements.txt I'm guessing some library release somewhere has caused this, I'll try and dig into it. All my dependencies are pinned but that's not to say their dependencies are.

Can you please share the requirments.txt as I have the same issue ?

**Comment by nroberts1** [comment] 2022-07-06 11:11
@Rupesh-rkgit depends how you do your pip install for dependencies. If you have a requirements.txt in the base of the project then just make sure it contains:
....
apache-beam==2.39.0
....
in it, this way it will use this version rather than getting the latest which is the one which causes TFX to break as above.
It you don't use requirements.txt then just use the command:
pip install apache-beam==2.39.0
you should notice at the end of this text that appears that there was an uninstall of apach beam 2.40.0

**Comment by robertwb** [comment] 2022-07-06 20:21
The root cause is an incorrect type declaration in `WriteStatsOutput`. Hopefully this will be fixed in the next version of TFX.

**Comment by pindinagesh** [comment] 2022-07-07 03:58
Hi @pSN0W 

Could you please move this issue to closed status as it is resolved. Thank you!

**Closed** 2022-07-07 04:48 UTC
Labels: type:bug, stat:awaiting response
