### ISSUE TITLE
TFX CLI with Kubeflow / AI Platform Pipelines runtime context missing when output is taken from cache

### ISSUE THREAD

**Issue by SaschaHeyer** [tensorflow/tfx#3375] opened 2021-03-15 06:59 UTC
**System information** 
- Have I specified the code to reproduce the issue
(Yes/No): no (Taxicab example works well)
- Environment in which the code is executed (e.g., Local
(Linux/MacOS/Windows), Interactive Notebook, Google Cloud, etc): AI Platform Pipelines
- TensorFlow version (you are using): /
- TFX Version: - Python version: 0.28.0

**Describe the current behavior**
The pipeline deployed with the TFX CLI runs into the following error

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 360, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/container_entrypoint.py", line 353, in main
    execution_info = launcher.launch()
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 198, in launch
    self._exec_properties)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/launcher/base_component_launcher.py", line 167, in _run_driver
    component_info=self._component_info)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/components/base/base_driver.py", line 270, in pre_execution
    driver_args, pipeline_info)
  File "/opt/conda/lib/python3.7/site-packages/tfx/dsl/components/base/base_driver.py", line 158, in resolve_input_artifacts
    producer_component_id=input_channel.producer_component_id)
  File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/metadata.py", line 948, in search_artifacts
    pipeline_info)
RuntimeError: Pipeline run context for PipelineInfo(pipeline_name: sentiment4, pipeline_root: gs://sascha-playground-doit-kubeflowpipelines-default/sentiment4, run_id: sentiment4-qnknl) does not exist
```

First run:
<img width="1216" alt="Screenshot 2021-03-15 at 07 40 55" src="https://user-images.githubusercontent.com/1991664/111114761-ff838d00-8563-11eb-9e87-ea649caaab66.png">

Second run with additional component
<img width="1216" alt="Screenshot 2021-03-15 at 07 51 28" src="https://user-images.githubusercontent.com/1991664/111114766-00b4ba00-8564-11eb-91f4-0fb1de4329e2.png">

Steps to reproduce

1. deploy pipeline with one component
2. run pipeline with one component (👍 works)
3. add another component
4. run the pipeline (this time the output is taken from cache)  (👎 fails)

Assume the second component doesn't find the cached data because the component did not exist in the first run. 

**Describe the expected behavior**
The second component get's executed

**Standalone code to reproduce the issue** 
Taxicab sample works fine as a test case

**Name of your Organization (Optional)**
/

**Other info / logs**

**Comment by SaschaHeyer** [comment] 2021-03-15 13:10
Kubeflow Pipelines reference https://github.com/kubeflow/pipelines/issues/5303

**Comment by jiyongjung0** [comment] 2021-03-16 01:59
Thank you so much for finding so many issues in TFX. 👍 

It seems weird. Because the caching logic is handled in KFP and TFX doesn't have much control over it, so I think that we need some help from KFP folks. By the way, I tried to reproduce this using our taxi template, but couldn't make it. Could you explain more on reproduction steps?

**Comment by ialdencoots** [comment] 2021-03-17 08:15
I am also running into this same problem.

**Comment by SaschaHeyer** [comment] 2021-03-17 20:55
@jiyongjung0 Did you tried the steps from above?

Steps to reproduce

1. deploy pipeline with one component
2. run pipeline with one component (👍 works)
3. add another component
4. run the pipeline (this time the output is taken from cache) (👎 fails)

If not I might can provide code for repdocution

**Comment by jiyongjung0** [comment] 2021-03-18 01:57
@SaschaHeyer Thank you for the explanation. I tried the steps you described.

1. Deploy a pipeline with just one component(ExampleGen) using `tfx pipeline create`
2. Run --> 👍 
3. Add the second component(StatGen) to the pipeline and update using `tfx pipeline update` -> This will re-build the container image.
4. Run --> All components re-run and succeed.

If you can provide more context, it would be great. Thanks.

**Comment by SaschaHeyer** [comment] 2021-03-18 18:40
I create a notebook for reproduction on the weekend. 

Just to make sure can you check if the first component did took the data from the cache during the second run. 
(This information is in the logs)

**Comment by jiyongjung0** [comment] 2021-03-18 23:00
No, ExampleGen ran from scratch again, and produced a new output. Thanks!

**Comment by SaschaHeyer** [comment] 2021-03-19 07:33
The error is only reproducible if the component took the data from cache.

**Comment by SaschaHeyer** [comment] 2021-03-24 18:49
@jiyongjung0 
Pipeline for reproduction https://github.com/SaschaHeyer/Sentiment-Analysis-TFX.
It's enough to just use the first two components for reproduction (like in the issue description)

**Comment by jiyongjung0** [comment] 2021-03-29 08:13
@SaschaHeyer Thanks for the information.

I tried your pipeline in my environment, but still couldn't reproduce the problem. When I added the second component and updated the pipeline, all components in the pipeline ran again without using cache.

I think that @Bobgy might give some help on this.

CC. @Bobgy

**Comment by SaschaHeyer** [comment] 2021-03-29 10:13
Interesting
Where did you run the pipeline? AI Platform Pipelines?

**Comment by jiyongjung0** [comment] 2021-03-30 03:01
Yes. I used my linux machine to trigger jobs on GCP Cloud AI Platform Pipelines. I tried to use the cloud build configs in your repository, but I couldn't figure out how can I create a "run" and update the pipeline with it.

I think that this issue is on Kubeflow Pipelines side, and it would be helpful if you can provide information like the content of pipeline package or detailed pipeline definition to kubeflow/pipelines#5303 although I'm not an expert on Kubeflow.

**Comment by Bobgy** [comment] 2021-06-10 22:24
Refer to https://github.com/kubeflow/pipelines/issues/5303#issuecomment-851904651, the bug is fixed on KFP 1.6.0, root cause is that KFP cache server used a hacky way to detect tfx pods, and it changed in newer versions.

I am working on releasing KFP 1.6.0+ to mkp

**Comment by sanatmpa1** [comment] 2022-01-07 16:30
@SaschaHeyer,

We are checking to see if this is still an issue, Can you take a look at the above comment from @Bobgy and let us know if it addresses your issue? Thanks!

**Comment by sanatmpa1** [comment] 2022-01-27 17:50
@SaschaHeyer,

Closing this issue due to lack of recent activity, Please feel free to reopen the issue with more details if the problem still persists. Thanks!

**Closed by sanatmpa1** 2022-01-27 17:50 UTC
Labels: type:bug, stat:awaiting response
