### ISSUE TITLE
tfx ImportExampleGen Payload_format issue

### ISSUE THREAD

**Issue by Rishabh-Choudhry** [tensorflow/tfx#4714] opened 2022-03-03 00:03 UTC
- Have I specified the code to reproduce the issue (Yes, No): No
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): Google Cloud
- TensorFlow version: 2.7.0
- TFX Version: > 1.5.0
- Python version: 3.7
- Python dependencies (from `pip freeze` output):

**Describe the current behavior**

When using 'example_gen_pb2.PayloadFormat.FORMAT_TF_SEQUENCE_EXAMPLE' payload_format in ImportExampleGen, transform component throws the following error:

> AssertionError: read_as_raw_records is specified - must provide raw_record_column_name

The code used for ImportExampleGen is :

`tfx.components.ImportExampleGen(input_base=data_path,input_config=example_gen_input_config,
                                           output_config=example_gen_output_config,
                                          payload_format=example_gen_pb2.PayloadFormat.FORMAT_TF_SEQUENCE_EXAMPLE)`

**Other info / logs**

> File "runner.py", line 138, in <module>
>     config_args = {'feature_config':"test", 'model_config':"test"}
>   File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/tfx_runner.py", line 116, in run
>     return self.run_with_ir(pipeline_pb, run_options=run_options_pb)
>   File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/local/local_dag_runner.py", line 109, in run_with_ir
>     component_launcher.launch()
>   File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 545, in launch
>     executor_output = self._run_executor(execution_info)
>   File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 420, in _run_executor
>     executor_output = self._executor_operator.run_executor(execution_info)
>   File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/beam_executor_operator.py", line 98, in run_executor
>     return python_executor_operator.run_with_executor(execution_info, executor)
>   File "/opt/conda/lib/python3.7/site-packages/tfx/orchestration/portable/python_executor_operator.py", line 59, in run_with_executor
>     execution_info.exec_properties)
>   File "/opt/conda/lib/python3.7/site-packages/tfx/components/transform/executor.py", line 576, in Do
>     TransformProcessor().Transform(label_inputs, label_outputs, status_file)
>   File "/opt/conda/lib/python3.7/site-packages/tfx/components/transform/executor.py", line 1068, in Transform
>     d.tfxio = self._CreateTFXIO(d, input_dataset_metadata.schema)
>   File "/opt/conda/lib/python3.7/site-packages/tfx/components/transform/executor.py", line 1623, in _CreateTFXIO
>     read_as_raw_records=read_as_raw_records)
>   File "/opt/conda/lib/python3.7/site-packages/tfx/components/util/tfxio_utils.py", line 302, in make_tfxio
>     'read_as_raw_records is specified - '
> AssertionError: read_as_raw_records is specified - must provide raw_record_column_name

**Comment by 1025KB** [comment] 2022-03-08 00:35
Zohar, do you know if TF_SEQUENCE_EXAMPLE is supported by Transform?

**Comment by gaikwadrahul8** [comment] 2022-12-14 08:09
@Rishabh-Choudhry 

Apologies for the delay and we have updated our official documentation with respect to `tf.train.SequenceExample()` [here](https://www.tensorflow.org/api_docs/python/tf/train/SequenceExample) and in above comment @zoyahav confirmed that currently SequenceExamples are supported by providing serialized SequenceExamples as a single feature to the preprocessing_fn which can then be decoded and proceed by the user. You can check our official documentation references [[1]](https://www.tensorflow.org/api_docs/python/tf/io/parse_single_sequence_example) [[2](https://www.tensorflow.org/api_docs/python/tf/io/parse_sequence_example)]

I found one [similar issue](https://github.com/tensorflow/tfx/issues/5520) where user has provided some workaround to use `SequenceExample` with Transform component [here](https://github.com/tensorflow/tfx/issues/5520#issuecomment-1328098474) could you please take look into that workaround and let us know Is it resolving your issue or not ? If issue still persists please let us know ?

Thank you!

**Comment by iindyk** [comment] 2022-12-14 13:38
Note that since version 1.10.0 TFX Transform supports `SequenceExample`s natively (i.e. no need to do parsing manually). To trigger the native path you need to specify `TensorRepresentaation`s in your schema, see example of such schema [here](https://github.com/tensorflow/transform/blob/master/examples/simple_sequence_example.py).

**Comment by gaikwadrahul8** [comment] 2023-01-30 04:54
Hi, @Rishabh-Choudhry 

One of our user @AlexanderLavelle has added complete approach how to use `tf.SequenceExample` records which is depending on the payload format in TFX transform component https://github.com/tensorflow/tfx/issues/5520#issuecomment-1382719616 you can refer that comment and please also refer  above comment by @iindyk I hope it will resolve your issue.

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update. Thank you!

**Closed** 2023-01-30 04:55 UTC
Labels: type:bug, stat:awaiting response
