### ISSUE TITLE
How to set environment variables for pipeline stages

### ISSUE THREAD

**Issue by dvaldivia** [tensorflow/tfx#5049] opened 2022-07-18 17:47 UTC
I'm trying to figure out how to set environment variables when creating a pipeline, the use case here is that I want to use S3 and I need to push down the credentials to `tensorflow-io` via environment variables, in previous releases of TFX when using reusable kubeflow components, I could simply add the environment variables, but if I try to use the built-in components and then compile them via DSL `KubeflowDagRunnerConfig` to a package, I don't see how I can set environment variables for individual stages.

Is the only option to wrap TFX native components in function components?

**Comment by jiyongjung0** [comment] 2022-07-22 02:24
Thank you for the question and it seems like a duplicate of https://github.com/tensorflow/tfx/issues/3326. I believe that @ConverJens is working on this in https://github.com/tensorflow/tfx/pull/4861.

**Comment by ConverJens** [comment] 2022-08-25 09:15
@dvaldivia 
I don't think it's possible to set any k8s value (resources, env vars, secrets etc) on individual steps but you can set them on the pipeline level using the 
```
kubeflow_dag_runner.KubeflowDagRunnerConfig(
    pipeline_operator_funcs=([your_func_to_set_env_vars_using_k8s_api(env_var_name, env_var_val)]
)
``` 
See my answer on this issue:
https://github.com/tensorflow/tfx/issues/3194

cc @jiyongjung0

**Comment by singhniraj08** [comment] 2022-11-04 06:01
@dvaldivia,

I see a PR #4861  merged which addresses this issue by enabling env. variables in beam_args through placeholders. This will be part of upcoming release. Please try the latest nightly build of TFX and let us know if this resolved your issue. Thank you!

**Comment by singhniraj08** [comment] 2023-02-01 06:23
Closing this due to inactivity. Please take a look into the answers provided above, feel free to reopen and post your comments(if you still have queries on this). Thank you!

**Closed by singhniraj08** 2023-02-01 06:23 UTC
Labels: type:docs, stat:awaiting response
