### ISSUE TITLE
How to pass trainer parameters to modelfile

### ISSUE THREAD

**Issue by yiyinying** [tensorflow/tfx#2703] opened 2020-10-26 15:57 UTC
I can’t understand the parameter passing, on the official website

**Comment by rmothukuru** [comment] 2020-10-27 11:02
@yiyinying
Please find the [TFX Trainer Documentation](https://www.tensorflow.org/tfx/guide/trainer) and the  [Example Module File](https://github.com/tensorflow/tfx/blob/master/tfx/examples/iris/iris_utils_native_keras.py).

If this doesn't answer your question, can you please elaborate on what exactly you need. Also, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by rmothukuru** [comment] 2020-11-04 07:17
@yiyinying,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment] 2020-11-11 06:58
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-11-11 06:58 UTC
Labels: stat:awaiting response, type:support
