### ISSUE TITLE
Add example with hyperparameters for Kubeflow

### ISSUE THREAD

**Issue by ianhellstrom** [tensorflow/tfx#38] opened 2019-04-10 07:28 UTC
It would be great if there would be an example on how to run TFX pipelines in Kubeflow with hyperparameters. Right now all the parameters are hard-coded, but having these exposed in the Kubeflow Pipelines UI (with defaults) would help with setting up a professional ML pipeline.

It's not entirely clear how to do this, so that `@PipelineDecorator` can pick these up. I presume they need to live in `input_dict` as `kfp.dsl.PipelineParam`s but a simple example would make that a lot easier to do.

**Comment by neuromage** [comment] 2019-04-11 16:41
Hi @ianhellstrom 

Am I correct in assuming that what you want is not hyperparameters, but that input parameters to a pipeline should be exposed in the Pipelines UI? If so, I definitely agree, and it's on my plate of things to do. Let's keep this as a feature request to track the work.

**Comment by ianhellstrom** [comment] 2019-04-17 11:38
Pipeline parameters, yes. Hyperparameters, maybe. What is the suggested approach for hyperparameters if not through the UI?

**Comment by DurivetMatthias** [comment] 2019-05-09 13:56
I'm also looking for a way to define a value once and have it available in every piece of code. This is especially difficult because the *_utils file is completely separated from the pipeline definition. For now the easiest way is to hard-code your values at the top of the *_utils file, and also do the same in the pipeline definition.

In my case I have a one_hot_encoding that influences the query in the pipeline definition and that same number is needed in the transform in the utils file where I actually encode them. The value i'm trying to pass is the vocabulary size

**Comment by neuromage** [comment] 2019-05-09 15:50
@DurivetMatthias  Ah interesting! Just so I understand correctly, you want an input parameter to a KFP pipeline to be accessible to both the query (which is defined in the pipeline definition file), as well as to some functions defined in the module file that's used as input to Transform?

**Comment by DurivetMatthias** [comment] 2019-05-09 16:07
Exactly

**Comment by ucdmkt** [comment] 2019-06-08 00:39
\cc @krazyhaas  

We are internally discussing to establish a design pattern to define and pass around intra-component  parameter (such as num_steps for Trainer), inter-component parameter applicable to more than one component that needed to be kept in sync  (such as @DurivetMatthias case) and pipeline-level global parameter.

**Comment by neuromage** [comment] 2019-09-27 17:46
Duplicate of #362

**Closed by neuromage** 2019-09-27 17:46 UTC
Labels: type:feature
