### ISSUE TITLE
airflow dag hangs long time and it is running state from last 2-3 hours

### ISSUE THREAD

**Issue by srikanthjoshi** [tensorflow/tfx#1289] opened 2020-02-18 15:38 UTC
Hi,

I have installed tfx, apache-airflow, tensorflow and I am able to run airflow webserver and scheduler both.

```
(srikanth) [root@brazossrik01 cc]# python -m pip list |grep tfx
tfx                        0.21.0             
tfx-bsl                    0.21.0             
(srikanth) [root@brazossrik01 cc]# python -m pip list |grep "tfx"
tfx                        0.21.0             
tfx-bsl                    0.21.0             
(srikanth) [root@brazossrik01 cc]# python -m pip list |grep tensorflow
tensorflow                 1.15.0             
tensorflow-data-validation 0.21.0             
tensorflow-estimator       1.15.1             
tensorflow-metadata        0.21.1             
tensorflow-model-analysis  0.21.1             
tensorflow-serving-api     1.15.0             
tensorflow-transform       0.21.0             
(srikanth) [root@brazossrik01 cc]# python -m pip list |grep apache-airflow
apache-airflow             1.10.9             
(srikanth) [root@brazossrik01 cc]# 
```

I clicked on chicago_taxi_example, it is in running state .

```
(srikanth) [root@brazossrik01 ~]# airflow scheduler
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2020-02-18 08:12:30,237] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-18 08:12:30,267] {scheduler_job.py:1344} INFO - Starting the scheduler
[2020-02-18 08:12:30,267] {scheduler_job.py:1352} INFO - Running execute loop for -1 seconds
[2020-02-18 08:12:30,268] {scheduler_job.py:1353} INFO - Processing each file at most -1 times
[2020-02-18 08:12:30,268] {scheduler_job.py:1356} INFO - Searching for files in /root/airflow/dags
[2020-02-18 08:12:30,273] {scheduler_job.py:1358} INFO - There are 24 files in /root/airflow/dags
[2020-02-18 08:12:30,273] {scheduler_job.py:1409} INFO - Resetting orphaned tasks for active dag runs
[2020-02-18 08:12:30,330] {base_job.py:316} INFO - Reset the following 1 TaskInstances:
        <TaskInstance: chicago_taxi_simple.CsvExampleGen 2020-02-18 13:59:57.542469+00:00 [None]>
[2020-02-18 08:12:30,336] {dag_processing.py:556} INFO - Launched DagFileProcessorManager with pid: 22417
[2020-02-18 08:12:30,340] {settings.py:54} INFO - Configured default timezone <Timezone [UTC]>
[2020-02-18 08:12:30,350] {dag_processing.py:758} WARNING - Because we cannot use more than 1 thread (max_threads = 2) when using sqlite. So we set parallelism to 1.

/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/orchestration/data_types.py:191: UserWarning: RuntimeParameter is only supported on KubeflowDagRunner currently.
  warnings.warn('RuntimeParameter is only supported on KubeflowDagRunner '
[2020-02-18 09:36:05,559] {component.py:137} WARNING - feature_slicing_spec is deprecated, please use eval_config instead.
[2020-02-18 09:36:06 -0600] [22840] [INFO] Handling signal: ttou
[2020-02-18 09:36:06 -0600] [30777] [INFO] Worker exiting (pid: 30777)
[2020-02-18 09:36:37 -0600] [22840] [INFO] Handling signal: ttin
[2020-02-18 09:36:37 -0600] [30991] [INFO] Booting worker with pid: 30991
[2020-02-18 09:36:37,574] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-18 09:36:37,576] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/orchestration/data_types.py:191: UserWarning: RuntimeParameter is only supported on KubeflowDagRunner currently.
  warnings.warn('RuntimeParameter is only supported on KubeflowDagRunner '
[2020-02-18 09:36:41,903] {component.py:137} WARNING - feature_slicing_spec is deprecated, please use eval_config instead.
[2020-02-18 09:36:42 -0600] [22840] [INFO] Handling signal: ttou
[2020-02-18 09:36:42 -0600] [30825] [INFO] Worker exiting (pid: 30825)
[2020-02-18 09:37:13 -0600] [22840] [INFO] Handling signal: ttin
[2020-02-18 09:37:13 -0600] [31036] [INFO] Booting worker with pid: 31036
[2020-02-18 09:37:13,950] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-18 09:37:13,951] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/orchestration/data_types.py:191: UserWarning: RuntimeParameter is only supported on KubeflowDagRunner currently.
  warnings.warn('RuntimeParameter is only supported on KubeflowDagRunner '
[2020-02-18 09:37:18,280] {component.py:137} WARNING - feature_slicing_spec is deprecated, please use eval_config instead.
[2020-02-18 09:37:18 -0600] [22840] [INFO] Handling signal: ttou
[2020-02-18 09:37:18 -0600] [30862] [INFO] Worker exiting (pid: 30862)
```

can u plz advice further ?

**Comment by gowthamkpr** [comment] 2020-02-19 18:18
@srikanthjoshi Clear everything and start running in a new environment and let me know if the issue still persists. Thanks!

**Comment by srikanthjoshi** [comment] 2020-02-20 10:29
I got to know why it is happening. airflow webserver is deleting psutil periodically :

(srikanth) [root@brazossrik01 ~]# airflow webserver
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2020-02-19 09:28:26,613] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-19 09:28:26,614] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/orchestration/data_types.py:191: UserWarning: RuntimeParameter is only supported on KubeflowDagRunner currently.
  warnings.warn('RuntimeParameter is only supported on KubeflowDagRunner '
[2020-02-19 09:28:30,838] {component.py:137} WARNING - feature_slicing_spec is deprecated, please use eval_config instead.
Running the Gunicorn Server with:
Workers: 4 sync
Host: 0.0.0.0:8080
Timeout: 120
Logfiles: - -
=================================================================            
[2020-02-19 09:28:32 -0600] [10745] [INFO] Starting gunicorn 19.10.0
[2020-02-19 09:28:32 -0600] [10745] [INFO] Listening at: http://0.0.0.0:8080 (10745)
[2020-02-19 09:28:32 -0600] [10745] [INFO] Using worker: sync
[2020-02-19 09:28:32 -0600] [10749] [INFO] Booting worker with pid: 10749
[2020-02-19 09:28:32 -0600] [10750] [INFO] Booting worker with pid: 10750
[2020-02-19 09:28:32 -0600] [10751] [INFO] Booting worker with pid: 10751
[2020-02-19 09:28:32 -0600] [10752] [INFO] Booting worker with pid: 10752
[2020-02-19 09:28:33,124] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-19 09:28:33,126] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
[2020-02-19 09:28:33,143] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-19 09:28:33,144] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
[2020-02-19 09:28:33,210] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-19 09:28:33,211] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
[2020-02-19 09:28:33,275] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-19 09:28:33,276] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
**rmdir /root/anaconda3/envs/srikanth/lib/python3.6/site-packages/psutil
rmdir /root/anaconda3/envs/srikanth/lib/python3.6/site-packages/psutil-5.6.7.dist-info**
/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/orchestration/data_types.py:191: UserWarning: RuntimeParameter is only supported on KubeflowDagRunner currently.
  warnings.warn('RuntimeParameter is only supported on KubeflowDagRunner ' 

[2020-02-19 09:29:12,927] {component.py:137} WARNING - feature_slicing_spec is deprecated, please use eval_config instead.
[2020-02-19 09:29:13 -0600] [10745] [INFO] Handling signal: ttou
[2020-02-19 09:29:13 -0600] [10749] [INFO] Worker exiting (pid: 10749)
[2020-02-19 09:29:44 -0600] [10745] [INFO] Handling signal: ttin
[2020-02-19 09:29:44 -0600] [11739] [INFO] Booting worker with pid: 11739
[2020-02-19 09:29:45,036] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-19 09:29:45,037] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
**rmdir /root/anaconda3/envs/srikanth/lib/python3.6/site-packages/psutil
rmdir /root/anaconda3/envs/srikanth/lib/python3.6/site-packages/psutil-5.7.0.dist-info**
/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/orchestration/data_types.py:191: UserWarning: RuntimeParameter is only supported on KubeflowDagRunner currently.
  warnings.warn('RuntimeParameter is only supported on KubeflowDagRunner '
[2020-02-19 09:29:49,258] {component.py:137} WARNING - feature_slicing_spec is deprecated, please use eval_config instead.
[2020-02-19 09:29:49 -0600] [10745] [INFO] Handling signal: ttou
[2020-02-19 09:29:49 -0600] [10750] [INFO] Worker exiting (pid: 10750)
[2020-02-19 09:30:20 -0600] [10745] [INFO] Handling signal: ttin
[2020-02-19 09:30:20 -0600] [12085] [INFO] Booting worker with pid: 12085
[2020-02-19 09:30:21,343] {__init__.py:51} INFO - Using executor SequentialExecutor
[2020-02-19 09:30:21,344] {dagbag.py:403} INFO - Filling up the DagBag from /root/airflow/dags
/root/anaconda3/envs/srikanth/lib/python3.6/site-packages/tfx/orchestration/data_types.py:191: UserWarning: RuntimeParameter is only supported on KubeflowDagRunner currently.
  warnings.warn('RuntimeParameter is only supported on KubeflowDagRunner '
[2020-02-19 09:30:25,673] {component.py:137} WARNING - feature_slicing_spec is deprecated, please use eval_config instead.

Please let me know what changes needs to be done in airflow such that it won't remove psutil.

**Comment by gowthamkpr** [comment] 2020-02-20 18:36
I am not able to reproduce this issue @srikanthjoshi

**Comment by srikanthjoshi** [comment] 2020-02-24 14:55
@gowthamkpr - I am able to consistently recreate this issue.. Are you trying to reproduce with same version(s) which I am using ?

**Comment by srikanthjoshi** [comment] 2020-02-26 17:31
@gowthamkpr - Any help I can get ?

**Comment by UsharaniPagadala** [comment] 2021-11-23 10:47
@srikanthjoshi 

Closing this issue.Please feel free to reopen if this still persists, and also refer [this](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/data_types.py#L169) .Thanks

**Closed by UsharaniPagadala** 2021-11-23 10:47 UTC
Labels: type:support, stat:awaiting tensorflower
