### ISSUE TITLE
KeyError: 'component_id'

### ISSUE THREAD

**Issue by valeriano-manassero** [tensorflow/tfx#437] opened 2019-08-07 12:01 UTC
With a build from master latest commit https://github.com/tensorflow/tfx/commit/c9c7ecc64fa050677c33d05038f4054b558e0eef

If I run a Kubeflow pipeline I got this from modelvalidator:
```
Traceback (most recent call last):
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 102, in <module>
    main()
  File "/tfx-src/tfx/orchestration/kubeflow/container_entrypoint.py", line 98, in main
    executor.run()
  File "/opt/venv/lib/python3.5/site-packages/tfx/orchestration/kubeflow/executor_wrappers.py", line 123, in run
    self._exec_properties)
  File "/opt/venv/lib/python3.5/site-packages/tfx/components/model_validator/executor.py", line 166, in Do
    component_id = exec_properties['component_id']
KeyError: 'component_id'
```

It's probably a bug but I'm not sure how to fix it. Any help will be appreciated.

**Comment by ruoyu90** [comment] 2019-08-07 18:05
Thanks for bringing up the issue @valeriano-manassero ! This bug is caused by the facts:
1. Kubeflow currently bypasses driver and publisher but only invokes executor
2. Model Validator executor references to a execution property that is populated by its driver

We will have a fix soon.

**Comment by ruoyu90** [comment] 2019-08-08 17:49
This should be fixed by https://github.com/tensorflow/tfx/commit/6283fffb3ac81e2f213b4895fbe19623dfa9c4f5

**Closed by ruoyu90** 2019-08-08 17:49 UTC
Labels: bug, stat:awaiting tensorflower

**Comment by valeriano-manassero** [comment] 2019-08-09 07:37
@ruoyu90 I can confirm bug is fixed.

Btw, with current master, for docker image build to be succesfull, we should fix a third party license import.
I already created this: https://github.com/tensorflow/tfx/pull/426

Anyone can review it pls?
