### ISSUE TITLE
Issue with running TFX sample code 

### ISSUE THREAD

**Issue by srinivasaraov** [tensorflow/tfx#1863] opened 2020-05-27 07:41 UTC
Traceback (most recent call last):
  File "tfx_sample.py", line 4, in <module>
    from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen
  File "/Users/sv/tfx_env/lib/python3.7/site-packages/tfx/components/__init__.py", line 20, in <module>
    from tfx.components.bulk_inferrer.component import BulkInferrer
  File "/Users/sv/tfx_env/lib/python3.7/site-packages/tfx/components/bulk_inferrer/component.py", line 24, in <module>
    from tfx.components.base import base_component
  File "/Users/sv/tfx_env/lib/python3.7/site-packages/tfx/components/base/base_component.py", line 28, in <module>
    from tfx.components.base import base_driver
  File "/Users/sv/tfx_env/lib/python3.7/site-packages/tfx/components/base/base_driver.py", line 28, in <module>
    from tfx.orchestration import metadata
  File "/Users/sv/tfx_env/lib/python3.7/site-packages/tfx/orchestration/metadata.py", line 36, in <module>
    from ml_metadata.metadata_store import metadata_store
  File "/usr/local/lib/python3.7/site-packages/ml_metadata/metadata_store/__init__.py", line 15, in <module>
    from ml_metadata.metadata_store.metadata_store import MetadataStore
  File "/usr/local/lib/python3.7/site-packages/ml_metadata/metadata_store/metadata_store.py", line 32, in <module>
    from ml_metadata.metadata_store import pywrap_tf_metadata_store_serialized as metadata_store_serialized
  File "/usr/local/lib/python3.7/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 28, in <module>
    _pywrap_tf_metadata_store_serialized = swig_import_helper()
  File "/usr/local/lib/python3.7/site-packages/ml_metadata/metadata_store/pywrap_tf_metadata_store_serialized.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tf_metadata_store_serialized', fp, pathname, description)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/ml_metadata/metadata_store/_pywrap_tf_metadata_store_serialized.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/lib/python3.7/site-packages/ml_metadata/metadata_store/_pywrap_tf_metadata_store_serialized.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.7/site-packages/ml_metadata/metadata_store/_pywrap_tf_metadata_store_serialized.so

Code I'm using is 

```
from tfx.utils.dsl_utils import csv_input
from tfx.components.example_gen.csv_example_gen.component import CsvExampleGen

examples = csv_input(os.path.join(base_dir, 'data/simple'))
example_gen = CsvExampleGen(input=examples);
```

Here's the version details of installed packages

apache-beam                    2.20.0
tensorboard                    1.15.0
tensorboard-plugin-wit         1.6.0.post3
tensorflow                     1.15.0
tensorflow-data-validation     0.23.0.dev0
tensorflow-estimator           1.15.1
tensorflow-metadata            0.22.0
tensorflow-model-analysis      0.21.5
tensorflow-serving-api         2.1.0
tensorflow-transform           0.22.0
tfx                            0.21.4
tfx-bsl                        0.22.0

Can someone help me resolve this issue?

**Comment by gowthamkpr** [comment] 2020-05-27 23:25
@srinivasaraov Can you please provide us the reproducible code to reproduce the issue. Thanks!

**Comment by srinivasaraov** [comment] 2020-05-28 03:53
@gowthamkpr : I'm using the code from https://www.tensorflow.org/tfx/guide/examplegen

**Comment by srinivasaraov** [comment] 2020-06-03 06:01
@gowthamkpr : Could you please let me know if you could reproduce this and found a fix for this?

**Comment by gowthamkpr** [comment] 2020-06-03 18:41
@srinivasaraov I don't run into any error running this code. I am attaching the .ipynb notebook that I used.
I am using
`tfx>=0.21.1,<0.22" "tensorflow>=2.1,<2.2" "tensorboard>=2.1,<2.3`
[example_gen.zip](https://github.com/tensorflow/tfx/files/4725506/example_gen.zip)
![image](https://user-images.githubusercontent.com/47574994/83676125-0cb02c00-a58f-11ea-96fb-70d8083e882c.png)

**Comment by srinivasaraov** [comment] 2020-06-04 04:39
@gowthamkpr : I could run this successfully on Google Colab. I ran into the error while running the same code locally (Mac OS).  Could you run this successfully locally?

**Comment by srinivasaraov** [comment] 2020-06-04 05:25
Also, what OS versions are supported for TFX?

**Comment by gowthamkpr** [comment] 2020-06-17 23:44
I was able to run it locally on Ubuntu 18.04

**Comment by rmothukuru** [comment] 2020-07-27 11:13
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-07-27 11:13 UTC
Labels: stat:awaiting response, type:support

**Comment by reflexiveprophecy** [comment] 2021-01-23 05:14
Had the same issue with TFX. Just like the error message said, I had to upgrade my Mac OS to 10.15 Catalina from 10.13 High Sierra in order to solve it...
