### ISSUE TITLE
ML Metadata store problem with optional ExecutionParameters

### ISSUE THREAD

**Issue by bcdurak** [tensorflow/tfx#1211] opened 2020-01-31 17:49 UTC
Hey there,

I am currently developing a pipeline on TFX 0.15 which utilizes numerous components including a bunch of custom components. 

In order to make it easier for me to query my metadata store, I would like to define my execution parameters in a granular way instead of merging them into a single execution parameter (such as a dict).

While running different configurations on components with such a structure, I have encountered a problem regarding their interaction with the MetadataStore, which can be explained with the following example:

Imagine the scenario, where a stand-alone custom component has three different ExecutionParameters, one of which is a mandatory parameter whereas the other two are optional. So, the respective ComponentSpec looks something like this:

```python
from tfx.types.component_spec import ComponentSpec, ExecutionParameter

class MyComponentSpec(ComponentSpec):
    PARAMETERS = {
        'a': ExecutionParameter(type=int, optional=False),
        'b': ExecutionParameter(type=int, optional=True),
        'c': ExecutionParameter(type=int, optional=True),
    }
    INPUTS = {}
    OUTPUTS = {}
```

As I create an instance of this component, I make sure that the execution parameter `a` is always present, however, `b` and `c` pop up depending on the experiment configuration.

Now, it is possible to run a pipeline with this component two consecutive times, if:

  - In the first run, only `a` is present and in the second run, `a` and `b` are both defined. 

  or
   
  - In the first run, both `a` and `b` are present, however in the second run, only `a` is defined.
  
So that means, first, I can run my component with a new and optional parameter (like `b` in the first example) even if my metadata store have not seen before. The corresponding execution type in the store will be updated via [`_prepare_execution_type`](https://github.com/tensorflow/tfx/blob/a28c09bf95420194d972e2598b1f969494bc8409/tfx/orchestration/metadata.py#L254) to include the new execution parameter. 

Secondly, I can run my component, even if I don't utilize an optional parameter (such as `b` in the second setting) that I have used and my metadata store registered before.

**However**, if I define `a` and `b` in the first run and then I proceed with `a` and `c` in the second run, both examples occur at the same time. Due to `c` being a new parameter it tries to update the execution type, but, since the `b` is missing, the function which is responsible for the update, namely [`put_execution_type`](https://github.com/google/ml-metadata/blob/bda170fadaf56e4e234441911bc1d74da5a7138b/ml_metadata/metadata_store/metadata_store.py#L301), fails.

As far as I could interpret it, the properties in a [`ExecutionType`](https://github.com/google/ml-metadata/blob/bda170fadaf56e4e234441911bc1d74da5a7138b/ml_metadata/proto/metadata_store.proto#L225) message has no notion whether an execution parameter is optional. Therefore, the only possible solution that I could find was to modify my `exec_properties` in each run to include at least a default value, so that [this statement](https://github.com/tensorflow/tfx/blob/a28c09bf95420194d972e2598b1f969494bc8409/tfx/orchestration/metadata.py#L274) will always hold true. However, this goes against the idea of having optional execution parameters in the components and can redundantly and significantly increase the size of the metadata store in an extended usage scenario.

**Comment by hughmiao** [comment] 2020-02-01 00:42
the root cause of this is currently tfx register the execution type on the fly when it sees the first instance, rather than register the schema based on the Parameters defined upfront. 

The current MLMD types enforce the type update should be back-ward compatible, i.e., 
{a} --> {a,c} -> {a,b,c} is ok
{a, b} --> {a,c} is not. 

A possible solution could be 
a) to register {a,b,c} upfront. 
b) allow breaking changes of the types

cc @ruoyu90 @charlesccychen to comment on this

**Comment by ruoyu90** [comment] 2020-02-01 01:16
@hughmiao is right. Our current [logic](https://github.com/tensorflow/tfx/blob/r0.15/tfx/types/component_spec.py#L163-L172) does not populate optional execution properties if not set. One possible solution based on current implementation is to populate default value for unset optional execution properties.

**Comment by UsharaniPagadala** [comment] 2021-11-23 12:13
@bcdurak 
Closing this issue based on the  above(@ruoyu90  ) comment.Please feel free to reopen if this is still an issue.Thanks

**Closed by UsharaniPagadala** 2021-11-23 12:13 UTC
Labels: type:performance
