### ISSUE TITLE
TFX Tutorial not working

### ISSUE THREAD

**Issue by ChristophToegel** [tensorflow/tfx#5609] opened 2022-12-25 10:58 UTC
The simple Penguin Tutorial doesn't seem to work any longer.

https://www.tensorflow.org/tfx/tutorials/tfx/penguin_simple?hl=de

Running it in colab reveals an import error.

> AttributeError                            Traceback (most recent call last)
> [<ipython-input-8-5fc0ef3a8fd9>](https://localhost:8080/#) in <module>
> ----> 1 tfx.orchestration.LocalDagRunner().run(
>       2   _create_pipeline(
>       3       pipeline_name=PIPELINE_NAME,
>       4       pipeline_root=PIPELINE_ROOT,
>       5       data_root=DATA_ROOT,
> 
> AttributeError: module 'tfx.v1' has no attribute 'orchestration'

Seems like some imports are missing in the "v1" directories.

TensorFlow version: 2.11.0
TFX version: 1.12.0
Python 3.8.16

**Comment by gaikwadrahul8** [comment] 2022-12-27 13:52
Hi, @ChristophToegel 

Apologize for the delay and I tried to reproduce the same error with latest versions `TFX==1.12.0` and `tensorflow==2.11.0 `and unfortunately same error is coming at the moment and I have tried different versions of `TFX==1.11.0` and `tensorflow==2.9.2` I'm getting the same error message which is related with `tfx.v1.orchestration.LocalDagRunner()`at the moment, I have attached Gist file [here](https://colab.research.google.com/gist/gaikwadrahul8/62029f16eda16cbf321850b367c9268f/penguin_simple.ipynb) so may be our team making some changes in code level because I'm unable to [view source on Github](https://github.com/tensorflow/tfx/blob/v1.12.0/tfx/orchestration/__init__.py) so I'll confirm with concerned team and I'll update the same here 

Thank you!

**Comment by gaikwadrahul8** [comment] 2022-12-29 07:31
Hi, @ChristophToegel 

I was able to replicate the issue without error now and for that you'll have to uninstall `shapely` by adding this line of code `!pip uninstall shapely -y `and even it's updated in google colab nootbook tutorials also, for your reference I have added gist file [penguin_simple](https://colab.research.google.com/gist/gaikwadrahul8/7ec9500e3848645a0939ff0f31d8cc8a/penguin_simple.ipynb)

Could you please try and confirm, Is it working both the tutorials as expected from your end ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ?

Thank you!

**Comment by ChristophToegel** [comment] 2022-12-29 20:15
Thank you  for your quick fix.
It works in the Colab versions, but not locally on my machine (Windows 10 with WSL interpreter Python at 3.9).
#5610 basiclly reports the same issue, so you might want to keep updates in that issue.

**Comment by gaikwadrahul8** [comment] 2022-12-30 06:51
Hi, @ChristophToegel 

Unfortunately TFX does not support Windows and there is currently no plan to support Windows, you can refer [similar-issue ](https://github.com/tensorflow/tfx/issues/950)and [comment](https://github.com/tensorflow/tfx/issues/950#issuecomment-970793241), Curently it supports both `Linux` and `MacOS` only. If you're using TFX for experimentation or learning purpose then I would suggest you to use in Google Colab

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ?

If you need any further assistance or if you have any further questions please feel free to ask.

Thank you!

**Closed** 2022-12-30 09:01 UTC
Labels: type:bug, stat:awaiting response

**Comment by hack-r** [comment] 2023-03-11 18:36
I'm a Linux user with tfx v1.12.0

The tutorial has several issues, one being "tfx.orchestration.LocalDagRunner" doesn't exist.

It has you do "from tfx import v1 as tfx" and "orchestration" doesn't exist at all in v1, but even if you find it in the higher-level tfx (meaning not v1) it still doesn't have "LocalDagRunner".

import tfx.v1 as tfx

dir(tfx)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'dsl',
 'proto',
 'types',
 'utils']

import tfx as tfx

dir(tfx.orchestration)

​

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'data_types',
 'experimental',
 'metadata',
 'pipeline',
 'portable']

I saw something saying it was moved to "experimental" but I don't see it in there either.

**Comment by hack-r** [comment] 2023-03-11 19:19
It looks like it needed me to try installing several different versions of scipy and 

apt install --reinstall python*-decorator

then it finally worked...

**Comment by uche-madu** [comment] 2023-04-18 04:50
I'm trying to go through the same tutorial on colab. I installed tfx (version 1.12.0) with `!pip install tfx -q` and uninstalled shapely `!pip uninstall shapely -y`, but I'm getting this error:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in requires(self, extras)
   2825             try:
-> 2826                 deps.extend(dm[safe_extra(ext)])
   2827             except KeyError as e:

KeyError: 'grpc'

The above exception was the direct cause of the following exception:

UnknownExtra                              Traceback (most recent call last)
22 frames
[/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py](https://localhost:8080/#) in requires(self, extras)
   2826                 deps.extend(dm[safe_extra(ext)])
   2827             except KeyError as e:
-> 2828                 raise UnknownExtra(
   2829                     "%s has no such extra feature %r" % (self, ext)
   2830                 ) from e

UnknownExtra: google-api-core 2.11.0 has no such extra feature 'grpc'

**Comment by uche-madu** [comment] 2023-04-18 05:11
> I'm trying to go through the same tutorial on colab. I installed tfx (version 1.12.0) with `!pip install tfx -q` and uninstalled shapely `!pip uninstall shapely -y`, but I'm getting this error:
> 
> KeyError Traceback (most recent call last) [/usr/local/lib/python3.9/dist-packages/pkg_resources/**init**.py](https://localhost:8080/#) in requires(self, extras) 2825 try: -> 2826 deps.extend(dm[safe_extra(ext)]) 2827 except KeyError as e:
> 
> KeyError: 'grpc'
> 
> The above exception was the direct cause of the following exception:
> 
> UnknownExtra Traceback (most recent call last) 22 frames [/usr/local/lib/python3.9/dist-packages/pkg_resources/**init**.py](https://localhost:8080/#) in requires(self, extras) 2826 deps.extend(dm[safe_extra(ext)]) 2827 except KeyError as e: -> 2828 raise UnknownExtra( 2829 "%s has no such extra feature %r" % (self, ext) 2830 ) from e
> 
> UnknownExtra: google-api-core 2.11.0 has no such extra feature 'grpc'

Never mind. As per the tutorial, restarting the colab runtime did the trick.
