### ISSUE TITLE
Installing TFX on CentOS 7.6

### ISSUE THREAD

**Issue by srinivasaraov** [tensorflow/tfx#1929] opened 2020-06-04 06:23 UTC
Can some one please list the Cent OS versions that TFX is compatible with?

**Comment by zhitaoli** [comment] 2020-08-17 20:05
@srinivasaraov Sorry I missed this issue.

We do not explicitly test TFX with Centos installations, because we do not run that environment ourselves. Therefore we don't really know which version of CentOS we are fully compatible with, beyond general sense of TFX and its dependency's general guidelines.

I think if you run into issues with installing TFX onto a clean CentOS docker image, we could take look as long as you provide  reproducible steps independent from your environment (ideally on Google cloud based VM/images). But this would also be best effort.

Please let us know if you think is not acceptable from an Open Source project perspective.

**Comment by arghyaganguly** [comment] 2021-04-20 08:47
Closing this based on the above comment trace.

**Closed by arghyaganguly** 2021-04-20 08:47 UTC
Labels: stat:awaiting response, type:build/install
