### ISSUE TITLE
Issue in TFX Trainer component

### ISSUE THREAD

**Issue by MERCHA** [tensorflow/tfx#2573] opened 2020-09-28 15:47 UTC
I get this issue when I'm trying to execute the following code
`from tfx.components import Trainer
from tfx.proto import trainer_pb2
from tfx.components.base import executor_spec
from tfx.components.trainer.executor import GenericExecutor

TRAINING_STEPS = 1000
EVALUATION_STEPS = 100

trainer = Trainer(
    module_file=trainer_file,
    custom_executor_spec=executor_spec.ExecutorClassSpec(GenericExecutor),
    examples=transform.outputs['transformed_examples'],
    schema=schema_gen.outputs['schema'],
    transform_graph=transform.outputs['transform_graph'],
    train_args=trainer_pb2.TrainArgs(num_steps=TRAINING_STEPS),
    eval_args=trainer_pb2.EvalArgs(num_steps=EVALUATION_STEPS))
context.run(trainer)`

The error message was 
`ValueError                                Traceback (most recent call last)
 in 
     15     train_args=trainer_pb2.TrainArgs(num_steps=TRAINING_STEPS),
     16     eval_args=trainer_pb2.EvalArgs(num_steps=EVALUATION_STEPS))
---> 17 context.run(trainer)

~/.local/lib/python3.6/site-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run_if_ipython(*args, **kwargs)
     65       # __IPYTHON__ variable is set by IPython, see
     66       # https://ipython.org/ipython-doc/rel-0.10.2/html/interactive/reference.html#embedding-ipython.
---> 67       return fn(*args, **kwargs)
     68     else:
     69       absl.logging.warning(

~/.local/lib/python3.6/site-packages/tfx/orchestration/experimental/interactive/interactive_context.py in run(self, component, enable_cache, beam_pipeline_args)
    175         telemetry_utils.LABEL_TFX_RUNNER: runner_label,
    176     }):
--> 177       execution_id = launcher.launch().execution_id
    178 
    179     return execution_result.ExecutionResult(

~/.local/lib/python3.6/site-packages/tfx/orchestration/launcher/base_component_launcher.py in launch(self)
    195                       self._component_info.component_id)
    196     execution_decision = self._run_driver(self._input_dict, self._output_dict,
--> 197                                           self._exec_properties)
    198 
    199     if not execution_decision.use_cached_results:

~/.local/lib/python3.6/site-packages/tfx/orchestration/launcher/base_component_launcher.py in _run_driver(self, input_dict, output_dict, exec_properties)
    164           driver_args=self._driver_args,
    165           pipeline_info=self._pipeline_info,
--> 166           component_info=self._component_info)
    167 
    168       return execution_decision

~/.local/lib/python3.6/site-packages/tfx/components/base/base_driver.py in pre_execution(self, input_dict, output_dict, exec_properties, driver_args, pipeline_info, component_info)
    275                                                    component_info)
    276     input_artifacts = self.resolve_input_artifacts(input_dict, exec_properties,
--> 277                                                    driver_args, pipeline_info)
    278     self.verify_input_artifacts(artifacts_dict=input_artifacts)
    279     absl.logging.debug('Resolved input artifacts are: %s', input_artifacts)

~/.local/lib/python3.6/site-packages/tfx/components/base/base_driver.py in resolve_input_artifacts(self, input_dict, exec_properties, driver_args, pipeline_info)
    158                 'components must first be run with '
    159                 '`interactive_context.run(component)` before their outputs can '
--> 160                 'be used in downstream components.') % (artifact, name))
    161         result[name] = artifacts
    162       else:

ValueError: Unresolved input channel Artifact(artifact: custom_properties {
  key: "name"
  value {
    string_value: "transformed_examples"
  }
}
custom_properties {
  key: "pipeline_name"
  value {
    string_value: "interactive-2020-09-28T17_35_41.198440"
  }
}
custom_properties {
  key: "producer_component"
  value {
    string_value: "Transform"
  }
}
, artifact_type: name: "Examples"
properties {
  key: "span"
  value: INT
}
properties {
  key: "split_names"
  value: STRING
}
properties {
  key: "version"
  value: INT
}
) for input 'examples' was passed in interactive mode. When running in interactive mode, upstream components must first be run with `interactive_context.run(component)` before their outputs can be used in downstream components.`

**Comment by gowthamkpr** [comment] 2020-09-28 17:00
@MERCHA Can you please reproduce the code in [colab](https://colab.sandbox.google.com/notebooks/welcome.ipynb) and share the gist. Thanks!

**Comment by lyschoening** [comment] 2020-10-01 12:00
@MERCHA Were you able to solve this issue?

I am having the same problem. Transform returns an examples artifact with an empty URI.

**Comment by lyschoening** [comment] 2020-10-01 12:02
As mentioned in https://github.com/tensorflow/tfx/issues/2500 this seems to be resolved in 0.24.

**Closed** 2020-10-01 15:01 UTC
Labels: stat:awaiting response, type:support
