### ISSUE TITLE
TFX 1.4.0 Issues

### ISSUE THREAD

**Issue by jay90099** [tensorflow/tfx#4472] opened 2021-11-17 18:03 UTC
Please comment or link any issues you find with TFX 1.4.0

Thanks.

**Comment by axeltidemann** [comment] 2021-12-03 09:50
I updated my pipeline from TFX 1.2.0, and at the same time started running on Vertex. I got two errors:

1. My custom component won't run, this is the error message: 
```
com.google.cloud.ai.platform.common.errors.AiPlatformException: code=INVALID_ARGUMENT, message=MetadataSchema must include a schema title that satisfies the following regex: ^[a-z][a-z0-9-_]{2,20}[.][A-Z][a-zA-Z0-9-_]{2,49}$, cause=null
```

2. I use `tensorflow/tfx:1.4.0` as the base image, but the CUDA libraries are not found. The GPU is attached (I can see that in `Vertex AI > Training > Custom Jobs`). This is the error message in the logs:
```
"2021-12-03 08:42:26.393910: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/lib/x86_64-linux-gnu:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
```

Any input would be greatly appreciated.

**Comment by dougkelly** [comment] 2021-12-06 04:33
I'm updating [pipeline code](https://github.com/GoogleCloudPlatform/training-data-analyst/tree/master/self-paced-labs/vertex-ai/vertex-pipelines/tfx) from TFX 1.2.0 to TFX 1.4.0 and having issues with the new `tfx.v1.orchestration.experimental.KubeflowV2DagRunner`.

I have narrowed it down to:
```
    runner = KubeflowV2DagRunner(
        config=KubeflowV2DagRunnerConfig(default_image=config.TFX_IMAGE_URI),
        output_filename=pipeline_definition_file,
    )

    return runner.run(pipeline, write_out=True)
```

which generates:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_26786/2609199920.py in <module>
      2     config=KubeflowV2DagRunnerConfig(),
      3     output_filename=pipeline_definition_file)
----> 4 _ = runner.run(test_pipeline)

/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/v2/kubeflow_v2_dag_runner.py in run(self, pipeline, parameter_values, write_out)
    159         default_image=self._config.default_image,
    160         default_commands=self._config.default_commands,
--> 161         exit_handler=self._exit_handler).build()
    162     pipeline_spec.sdk_version = 'tfx-{}'.format(version.__version__)
    163     pipeline_spec.schema_version = _SCHEMA_VERSION

/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/v2/pipeline_builder.py in build(self)
    142             enable_cache=self._pipeline.enable_cache,
    143             pipeline_info=self._pipeline_info,
--> 144             channel_redirect_map=channel_redirect_map).build()
    145         tfx_tasks.update(built_tasks)
    146 

/opt/conda/lib/python3.7/site-packages/tfx/orchestration/kubeflow/v2/step_builder.py in build(self)
    334                                                   (producer_id, output_key))[1]
    335       input_artifact_spec = pipeline_pb2.TaskInputsSpec.InputArtifactSpec()
--> 336       input_artifact_spec.task_output_artifact.producer_task = producer_id
    337       input_artifact_spec.task_output_artifact.output_artifact_key = output_key
    338       task_spec.inputs.artifacts[name].CopyFrom(input_artifact_spec)

TypeError: None has type NoneType, but expected one of: bytes, unicode
```

Any help is greatly appreciated.

**Comment by aybchan** [comment] 2021-12-10 10:29
>@axeltidemann 
> I use tensorflow/tfx:1.4.0 as the base image, but the CUDA libraries are not found. The GPU is attached (I can see that in Vertex AI > Training > Custom Jobs).

I also had this exact issue on Vertex after updating my component base images from `tensorflow/tfx:1.2.0` to `tensorflow/tfx:1.4.0`

**Comment by jiyongjung0** [comment] 2021-12-13 10:11
@axeltidemann @aybchan Thank you for the report! It seems like we have an issue in resolving corresponding CUDA versions. TFX container image is based on Google Cloud Deep Learning Container images, but unfortunately we have re-installed `tensorflow==2.6.2` while building the image for TFX 1.4.0, and it made the linked CUDA version different.

```
python -c 'import tensorflow; print(tensorflow.sysconfig.get_build_info())'
OrderedDict([('cpu_compiler', '/usr/bin/gcc-5'), ('cuda_compute_capabilities', ['sm_35', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'compute_80']), ('cuda_version', '11.2'), ('cudnn_version', '8'), ('is_cuda_build', True), ('is_rocm_build', False), ('is_tensorrt_build', True)])
```
The installed cuda library in the image is 11.0 in the image. This happened because at the time of 1.4.0 release, TF 2.6.2 release was not available in the Google Cloud Deep Learning Container image.

We might need to rebuild the image.(And should add some sort of safety mechanism to catch this.) Before that, may I ask a favor to confirm that the root cause is the CUDA version mismatch? Could you try `tensorflow/tfx:1.3.4` version if possible? It is released after `1.4.0` and it has tensorflow that is built with CUDA==11.0.

```
python -c 'import tensorflow; print(tensorflow.sysconfig.get_build_info())'
OrderedDict([('cpu_compiler', '/usr/bin/gcc-5'), ('cuda_compute_capabilities', ['compute_37', 'compute_60', 'compute_61', 'compute_70', 'compute_75', 'compute_80']), ('cuda_version', '11.0'), ('cudnn_version', '8'), ('is_cuda_build', True), ('is_rocm_build', False), ('is_tensorrt_build', True)])
```

**Comment by axeltidemann** [comment] 2021-12-14 14:36
It is for sure the CUDA mismatch - I manually built `tensorflow/tfx:1.6.0.dev` from master and the GPU was used.

**Comment by jiyongjung0** [comment] 2021-12-15 01:34
@axeltidemann Thank you for confirmation. We released TFX 1.5.0 today, and it should work with GPUs. (Although it requires TF 2.7) We will work on the patch release(1.4.1?) and produce the container image again.

**Comment by jiyongjung0** [comment] 2021-12-20 02:48
FYI, we already have entered the holiday freeze season and no release is expected until next year. Sorry for the delay.

**Comment by jiyongjung0** [comment] 2022-01-21 01:39
TFX 1.4.1 including the fix released. Sorry for the delay.

**Closed** 2022-05-20 18:07 UTC
Labels: type:bug
