### ISSUE TITLE
BigQueryExampleGen does not support creating functions or temporary tables

### ISSUE THREAD

**Issue by casassg** [tensorflow/tfx#2119] opened 2020-07-09 23:53 UTC
As a user of BigQueryExampleGen I would expect to be able to still use bigquery functions in my query. This is rendered impossible due to TFX trying to run the [query as a subquery](https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_big_query/example_gen/executor.py#L36) as subqueries dont allow you to create temporary functions. 

If we can get at least a way to create temporary functions, that would be neat

Wondering if there's a better method for getting the expected schema when using BigQuery instead of running the whole query as a subquery.

**Comment by zhitaoli** [comment] 2020-07-10 16:02
The link you mentioned is only to extract the type information of each field.

The actual big query is performed by a beam PTramsform ReadFromBigQuery, which is defined [here](https://github.com/apache/beam/blob/8fc613a6bd4815e146ffd4a7a01863c142d4267c/sdks/python/apache_beam/io/gcp/bigquery.py#L1659)

My quick scan shows that it might not offer the temp function (at least not explicitly in named kwargs). Maybe consider raising this as an apache/beam issue?

**Comment by casassg** [comment] 2020-07-10 16:15
Yup, it fails in the extract type information actually. Seems BigQuery does not accept create temp functions on subqueries. 


Aka if my query is:

```
CREATE TEMP FUNCTION x AS ....;

SELECT * FROM a WHERE x(a.a)=='a';
```

This fails as it can't run as a subquery. BigQueryExampleGen tries to run this to infer column types:
```
SELECT * FROM (
CREATE TEMP FUNCTION x AS ....;

SELECT * FROM a WHERE x(a.a)=='a';
) LIMIT 0;
```
^ This is an invalid BigQuery syntax. `Syntax error: Unexpected keyword CREATE at [2:1]`

**Comment by 1025KB** [comment] 2020-07-10 22:18
What Zhitao means above is even we drop the subquery for schema and provide schema in other way

that query may not be supported by [ReadFromBigQuery] (https://github.com/tensorflow/tfx/blob/master/tfx/extensions/google_cloud_big_query/example_gen/executor.py#L100) as it might only support single sql statement

**Comment by casassg** [comment] 2020-07-10 23:31
So after some further investigation you were totally right. Seems ReadFromBigQuery not the old BigQuerySource do not support scripts:

```
{
  "error": {
    "code": 400,
    "message": "configuration.query.destinationTable cannot be set for scripts",
    "errors": [
      {
        "message": "configuration.query.destinationTable cannot be set for scripts",
        "domain": "global",
        "reason": "invalid"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

Filed a ticket w Beam to see if they can recommend an alternative approach or if it can be added to their roadmap: https://issues.apache.org/jira/browse/BEAM-10461

Thanks for the help!

**Comment by rmothukuru** [comment] 2020-07-13 05:33
@casassg,
As the issue is related to Apache Beam, can you please let us know if we can close this issue. Thanks!

**Comment by casassg** [comment] 2020-07-13 05:42
Yup, all good!

**Closed** 2020-07-13 05:42 UTC
Labels: stat:awaiting response, type:others

**Comment by entrpn** [comment] 2021-06-02 21:41
I have a use case where I want to run queries as part of the pipeline without getting the results for preprocessing. I solved it by creating my own custom component. Maybe this is what is needed for this usecase as well. Example:

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from typing import Optional

from google.cloud import bigquery

from tfx.dsl.component.experimental.annotations import OutputDict, Parameter
from tfx.dsl.component.experimental.decorators import component

@component
def BigQueryRunner(
  query: Parameter[str]) -> OutputDict(success=int):
  """
  Constructs BigQueryRunner. This component runs a query and waits for completion. 

  Args: 
    query: BigQuery sql string.
  Returns:
    outputdict with success = True if query was ran successfuly.
  """

  success = 1

  try:
    client = bigquery.Client()
    query_job = client.query(query)

    #wait for query to complete
    query_job.result()   
  except:
    success = 0
    # todo - log error in return artifact.
    pass

  return {
    'success': success
  }
```
