### ISSUE TITLE
error while running the codes in Colab @ the **Make REST requests** section

### ISSUE THREAD

**Issue by BuggieCoder** [tensorflow/tfx#5113] opened 2022-08-05 17:28 UTC
Got the following error while running the codes in Colab and reaching this section (second to last section)

**Make REST requests
Newest version of the servable**

**Cell**:

`# docs_infra: no_execute
!pip install -q requests

import requests
headers = {"content-type": "application/json"}
json_response = requests.post('http://localhost:8501/v1/models/fashion_model:predict', data=data, headers=headers)
predictions = json.loads(json_response.text)['predictions']

show(0, 'The model thought this was a {} (class {}), and it was actually a {} (class {})'.format(
  class_names[np.argmax(predictions[0])], np.argmax(predictions[0]), class_names[test_labels[0]], test_labels[0]))`

**Error messages**

ConnectionRefusedError                    Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/urllib3/connection.py](https://localhost:8080/#) in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
    160 

19 frames
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ff012199d10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
MaxRetryError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/fashion_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff012199d10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/requests/adapters.py](https://localhost:8080/#) in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/fashion_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff012199d10>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by sanatmpa1** [comment] 2022-08-10 17:48
@BuggieCoder 

I guess you're trying to run [this example notebook](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple) and I am able to reproduce the issue when running in colab. I will get back to you after trying on local environment and see if it still happens. Thank you!

**Comment by BuggieCoder** [comment] 2022-08-10 21:23
@sanatmpa1 Thank you for doing that. Yes, I got the error in Colab.

**Comment by gaikwadrahul8** [comment] 2022-10-21 09:18
@BuggieCoder 

It seems like duplicate issue like [#2054](https://github.com/tensorflow/serving/issues/2054) and As workaround please comment this line : `!{SUDO_IF_NEEDED} apt-get install tensorflow-model-server `line and add below 03 lines of command to install Tensorflow serving 2.8.0 in section : **Install TensorFlow Serving**

```
!wget 'http://storage.googleapis.com/tensorflow-serving-apt/pool/tensorflow-model-server-2.8.0/t/tensorflow-model-server/tensorflow-model-server_2.8.0_all.deb'
!dpkg -i tensorflow-model-server_2.8.0_all.deb
!pip3 install tensorflow-serving-api==2.8.0

```

Sharing the working [gist file](https://colab.research.google.com/gist/gaikwadrahul8/94387f4ce95bd0dffb0639bb5b8bff70/rest_simple.ipynb) for reference. Can you please close this issue, since it is already being tracked on https://github.com/tensorflow/serving/issues/2054.

Thank you!

**Comment by BuggieCoder** [comment] 2022-10-24 21:29
Thank you for your response. Will close the issue.

**Closed** 2022-10-24 21:29 UTC
Labels: type:support
