### ISSUE TITLE
Cannot run Github Action: Could not install packages due to an OSError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by lego0901** [tensorflow/tfx#6956] opened 2024-11-15 04:42 UTC
This issue has persisted for a while, hindering our ability to run unit tests.

**Comment by janasangeetha** [comment] 2024-11-26 08:26
Closing the issue as the [PR](https://github.com/tensorflow/tfx/pull/7635) is merged and the issue is resolved.

**Closed by janasangeetha** 2024-11-26 08:26 UTC
Labels: type:bug
