### ISSUE TITLE
BigQueryExampleGen fails on Kubeflow Pipelines when using long queries

### ISSUE THREAD

**Issue by codesue** [tensorflow/tfx#4295] opened 2021-09-22 21:39 UTC
**System information**

- Have I specified the code to reproduce the issue (Yes, No): Yes
- Environment in which the code is executed (e.g., Local(Linux/MacOS/Windows),
  Interactive Notebook, Google Cloud, etc): MacOS
- TensorFlow version: `tensorflow==2.4.2`
- TFX Version: `0.26.3` but it might also affect the master branch
- Python version: `Python 3.7.7`
- Python dependencies (from `pip freeze` output): Irrelevant

**Describe the current behavior**
BigQueryExampleGen fails on Kubeflow Pipelines with the error `standard_init_linux.go:211: exec user process caused "argument list too long"` due to the length of the tfx_ir / serialized_component arg when using long queries. This is a blocker for us.

**Describe the expected behavior**
BigQueryExampleGen should not fail on Kubeflow Pipelines, even when using long queries.

**Standalone code to reproduce the issue**
Run BigQueryExampleGen with a query that selects ~500 features to cause the tfx_ir / serialized_component string to exceed ~131k characters.

**Name of your Organization (Optional)** Twitter

**Other info / logs**

This (TFX IR exceeding the flag size limit) is a known issue and there's a [TODO to fix it](https://github.com/tensorflow/tfx/blob/master/tfx/orchestration/kubeflow/base_component.py#L105) in the TFX component to KFP operator conversion logic. The suggested fix is writing the IR to the pipeline_root and letting container_entrypoint.py read it back. There seems to be a PR that could have resolved this, but it was marked stale and automatically closed: https://github.com/tensorflow/tfx/pull/3842. Relevant changes from that PR are in https://github.com/tensorflow/tfx/pull/4298. A PR to remove extra node information in the generated IR (https://github.com/tensorflow/tfx/pull/3992) merged after this was proposed, and I'm not sure if those changes would still be necessary when persisting the IR to a file instead of using a string.

**Comment by casassg** [comment] 2022-03-10 22:23
@rcrowe-google  any chance to tag this to Twitter ?

**Comment by 1025KB** [comment] 2022-03-10 22:32
For long queries, there are multiple limitations, e.g., mlmd exec properties field size, tfx ir size etc.
Consider create a custom component that instead of passing in the query, it passes the file path with query in it, maybe name the file with its fingerprint or sth to make sure caching still work properly.

**Comment by rcrowe-google** [comment] 2022-03-15 18:39
Would a [stored procedure](https://cloud.google.com/bigquery/docs/reference/standard-sql/scripting-concepts) be a workable solution for long queries?  It would allow for the complexity of the query to be saved and invoked with a shorter query.

**Comment by casassg** [comment] 2022-03-15 19:37
We have been using views as an alternative yes. But it makes for versioning difficult as one needs to update those separately.

Regarding uploading it works, however the issue is we need to fork and retrieve the file on driver as we still need to resolve fields in the SQL query. So it's problematic

**Comment by iain-stitt-by** [comment] 2022-03-16 08:38
Following up on this thread to post our updated solution given recent activity. 

We looked at the various options discussed here, such as VIEWS etc, but decided against those since as @casassg  rightly points out versioning is very important and would be lost using this mechanism. Another thing we considered was compressing/decompressing the query string to reduce length, but this impacts the easy readability of pipeline inputs and would introduce undesired dependency on other modules to compress/decompress. 

Similar to what @1025KB  is suggesting, we created a custom QueryGen component that creates the query programmatically and stores it as an output artifact text file. Then we modified the out of the box big query examplegen component to read a Channel of type Query. We also modified the executor code to read the specified QueryGen artifact text files and  inject the query strings in the necessary places.

**Comment by rcrowe-google** [comment] 2022-03-16 16:49
@iain-stitt-by that sounds like a useful approach that others might benefit from.  Would you consider contributing it to [TFX-Addons](https://github.com/tensorflow/tfx-addons)?

**Comment by iain-stitt-by** [comment] 2022-03-18 08:13
Sure @rcrowe-google , we can look into adding some of our custom components to the TFX-Addons project

**Comment by singhniraj08** [comment] 2023-05-31 10:09
@codesue,

Instead of writing the IR to the pipeline_root and letting container_entrypoint.py read it back, we have made some internal changes to mitigate this issue. The changes include stopping to pass "serialized_component" in arguments list and removing unnecessary whitespaces. Since IR stack migration and following cleanup is completed internally, you can use latest TFX release to make sure this issue is resolved. 

Pleas let us know if this issue is resolved for you. Thank you!

**Comment by codesue** [comment] 2023-06-01 07:44
Thank you for the fix and for following up on this, @singhniraj08! I'm no longer actively working on this, so this issue is resolved for my purposes.

**Comment by singhniraj08** [comment] 2023-06-05 05:54
@codesue, 

Thanks for the confirmation. Closing this issue.

**Closed by singhniraj08** 2023-06-05 05:54 UTC
Labels: type:bug, Twitter
