### ISSUE TITLE
Is there any dashboard like visualization project for the ml-metadata ?

### ISSUE THREAD

**Issue by yupbank** [tensorflow/tfx#18] opened 2019-03-21 13:44 UTC
It would be amazing if we have that type of project, would win a lot of heart to on board  ml-metadata!

**Comment by npoly** [comment] 2019-03-21 16:36
Can you clarify the type of functionality that you would find useful in this dashboard? Would it help to provide tooling/libraries that provide ml-metadata exploration inside a Jupyter notebook?

**Comment by MattMorgis** [comment] 2019-04-05 13:27
>Would it help to provide tooling/libraries that provide ml-metadata exploration inside a Jupyter notebook?

Yes, that would be great! We are still working with the examples right now, but have been diving in the the actual sqlite database, but this has been more exploratory. As we continue to move from the examples to our own pipelines I can update with more details about what we'd like to see exposed in some fashion.

**Comment by npoly** [comment] 2019-05-10 17:35
I would advise against poking in the internals of the db since those can change. 

In the meantime, you can see different ways to browse the metadata from a notebook here: https://www.tensorflow.org/tfx/tutorials/tfx/workshop

**Comment by krazyhaas** [comment] 2019-05-21 20:00
I'm closing this one as a duplicate of https://github.com/google/ml-metadata/issues/8.

**Closed** 2019-05-21 20:01 UTC
Labels: stat:awaiting response, type:feature
