### ISSUE TITLE
docs/tutorials/tfx/components_keras.ipynb broken when running on Google Colab

### ISSUE THREAD

**Issue by jingtaow** [tensorflow/tfx#1704] opened 2020-04-29 15:52 UTC
This notebook is the example shown in the "TFX Keras Component Tutorial" on the tensorflow.org website, i.e. https://www.tensorflow.org/tfx/tutorials/tfx/components_keras .

After clicking the recommended option "Run in Google Colab" and running the first  cell - "Installing TFX"in Google Colab, it generates the following errors:

----ERROR LOG----
`
ERROR: tensorflow 2.1.0 has requirement tensorboard<2.2.0,>=2.1.0, but you'll have tensorboard 2.2.1 which is incompatible.
ERROR: tensorflow-probability 0.10.0rc0 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
ERROR: qtconsole 4.7.3 has requirement pyzmq>=17.1, but you'll have pyzmq 17.0.0 which is incompatible.
ERROR: pydrive 1.3.1 has requirement oauth2client>=4.0.0, but you'll have oauth2client 3.0.0 which is incompatible.
ERROR: multiprocess 0.70.9 has requirement dill>=0.3.1, but you'll have dill 0.3.0 which is incompatible.
ERROR: google-colab 1.0.0 has requirement pandas~=1.0.0; python_version >= "3.0", but you'll have pandas 0.25.3 which is incompatible.
ERROR: google-api-python-client 1.7.12 has requirement httplib2<1dev,>=0.17.0, but you'll have httplib2 0.12.0 which is incompatible.
ERROR: kubernetes 10.1.0 has requirement pyyaml~=3.12, but you'll have pyyaml 5.3.1 which is incompatible.
`
----END OF ERROR LOG----

It seems that the the default version numbers in the components_keras.ipynb needs to be updated after the package upgrades in Google Colab.

**Comment by jiyongjung0** [comment] 2020-05-04 02:34
Thank you for reporting this.
As the number of dependent packages grows, it is getting harder to ensure every dependency not to conflict to each other. We are currently working on possible solutions to resolve root cause of these conflicts.

**Comment by KrishnaRekapalli** [comment] 2020-06-03 21:42
@jiyongjung0 Can I work on this issue? This is my first time contributing to an opensource project.

**Comment by jiyongjung0** [comment] 2020-06-04 01:06
Thank you for your interest. Krishna! Can you share your idea with us before actually implementing it? I'd like to make sure that we have consistent future plan for this.

FYI, tfx 0.22.0rc is out and tfx 0.22.0 will be released soon, and I think that we need to update the versions of dependent packages, too.

**Comment by KrishnaRekapalli** [comment] 2020-06-04 14:07
@jiyongjung0 I haven't found a fix yet! I wanted to give it a shot. I would love to get some direction. I was attempting if changing the versions in pip install should fix it. But looks like some packages have conflicting version dependencies. 

When you say a consistent plan, you're thinking about breaking this issue into multiple PRs?

**Comment by jiyongjung0** [comment] 2020-06-05 01:41
I meant that it would be better if your approach is consistent with other project members/contributors who are working on this dependency problem. 

Changing some versions might be a solution, but it seems not easy to specify all compatible versions. And I don't think that specifying all versions of dependent packages just for the conflict resolution which is fragile as packages are updated and we need to follow those upgrades. So we couldn't find simple and robust solution yet. Any help from you would be appreciated! 😄

**Closed** 2021-04-22 00:48 UTC
Labels: type:bug
