### ISSUE TITLE
How to automatically calcuate class weights for imbalanced classes?

### ISSUE THREAD

**Issue by lipinski** [tensorflow/tfx#1549] opened 2020-03-27 08:20 UTC
Hi,

Many real problems have an imbalanced data set. We can use undersampling or class weights, but is there a method to automatically calculate and add class weights to estimators. I know how to add class weights to estimator, but I don't know how to calculate automatically using TFX.

**Comment by Bumbleblo** [comment] 2020-03-27 10:50
@lipinski you know/read that [documentation](https://www.tensorflow.org/tutorials/structured_data/imbalanced_data#calculate_class_weights) ? I believe that you can solve that using just keras / estimator API.

**Comment by lipinski** [comment] 2020-03-27 10:55
Yes, I read and know. I don't want to calculate this manually, because imbalance in the data can changes over time. I am looking for solution in TFX.

**Comment by 1025KB** [comment] 2020-03-27 18:11
Hi, @lipinski, what mentioned by @Bumbleblo is the current solution we supported, in addition to that, StatsGen should help you analysis the input data and decided the class weight, Schema and ExampleValidator can be used to monitoring the data distribution.

@paulgc, is there anything specific for class weight in StatsGen?

**Comment by ucdmkt** [comment] 2020-03-30 06:25
@lipinski One approach to dynamically calculate such weight is to dynamically calculate and add an additional  feature that indicates class weights into records by Transform ([`tft.count_per_key`](https://github.com/tensorflow/transform/blob/master/tensorflow_transform/analyzers.py#L638) would be useful here). 

You will need to make sure that such transformation and the weight feature is only added and available at training time, though.

**Comment by 1025KB** [comment] 2020-03-30 06:37
re @ucdmkt, iiuc, that method is different as the one mentioned in [documentation](https://www.tensorflow.org/tutorials/structured_data/imbalanced_data#calculate_class_weights) (the class weights in provided at compile time)

**Comment by paulgc** [comment] 2022-02-17 18:02
TFDV currently provides top-k frequency counts for categorical features which can help with calculating class weights. But the actual computation of weights should happen outside of TFDV.

**Comment by gowthamkpr** [comment] 2022-08-12 16:42
@lipinski Please use [Addons component for sampling](https://github.com/tensorflow/tfx-addons/tree/main/tfx_addons/sampling) as mentioned [here](https://github.com/tensorflow/tfx/issues/3831#issuecomment-913872664). Also, can you please close the issue as its a duplicate of the issue #3831. Thanks!

**Closed** 2022-08-12 16:43 UTC
Labels: type:feature, stat:awaiting tensorflower
