### ISSUE TITLE
BeamDagRunner, Transform deadlock with Python 3.6

### ISSUE THREAD

**Issue by tkakantousis** [tensorflow/tfx#928] opened 2019-11-12 15:26 UTC
Hi everyone,

Running the `taxi_pipeline_beam` example fails with 
```
  from tensorflow_transform.output_wrapper import TFTransformOutput
  File "/srv/hops/anaconda/anaconda/envs/python36/lib/python3.6/site-packages/tensorflow_transform/output_wrapper.py", line 29, in <module>
    from tensorflow_transform.tf_metadata import metadata_io
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 149, in __enter__
  File "<frozen importlib._bootstrap>", line 94, in acquire
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('tensorflow_transform.tf_metadata.metadata_io') at 139642620901192
```
while running Transform https://github.com/tensorflow/tfx/blob/0.14.0/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_beam.py#L85

TFX version is 0.14, Beam is 2.15 and running on Flink 1.8.1.

All works well with Python 2.7. Has anyone encountered this issue before?

Thank you,
Theo

**Comment by tvalentyn** [comment] 2019-11-13 02:49
Hi, @tkakantousis. Thanks a lot for reporting this. We have seen an issue [reported](https://lists.apache.org/thread.html/5581ddfcf6d2ae10d25b834b8a61ebee265ffbcf650c6ec8d1e69408@%3Cdev.beam.apache.org%3E) on Beam mailing list, that may be similar in nature, but we have not yet rootcaused it.
Do you know if this error is reproducible in your setup on Python 3.7.3 or higher?

**Comment by tkakantousis** [comment] 2019-11-13 10:00
Hi @tvalentyn 
Thank you for looking into the issue. Same error with Python3.7.3 but in TFMA this time, it worked for Transform
```
File "/srv/hops/anaconda/anaconda/envs/python373/lib/python3.7/site-packages/tensorflow_model_analysis/evaluators/__init__.py", line 20, in <module>
    from tensorflow_model_analysis.evaluators.metrics_and_plots_evaluator import MetricsAndPlotsEvaluator
  File "/srv/hops/anaconda/anaconda/envs/python373/lib/python3.7/site-packages/tensorflow_model_analysis/evaluators/metrics_and_plots_evaluator.py", line 26, in <module>
    from tensorflow_model_analysis.evaluators import aggregate
  File "<frozen importlib._bootstrap>", line 980, in _find_and_load
  File "<frozen importlib._bootstrap>", line 149, in __enter__
  File "<frozen importlib._bootstrap>", line 94, in acquire
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock('tensorflow_model_analysis.evaluators.aggregate') at 140200765413696
 [while running 'Run[ModelValidator]']
```

**Comment by tvalentyn** [comment] 2019-11-14 01:47
Thanks. I am trying to reproduce this locally, just wanted to double check - how do you launch this example? 
I've tried so far ```python tfx/examples/chicago_taxi_pipeline/taxi_pipeline_beam.py``` which worked for me on Python 3.5, 3.7.5, but I believe that does not involve Beam on Flink. 
I am working on Beam primarily, and looks like there were a quite a few changes since the last time I played with Chicago taxi example.

**Comment by tkakantousis** [comment] 2019-11-14 09:23
Hi,
I copied the example into an iPython notebook and I ran it from Jupyter. As you suggested it most probably is a Beam issue with Python, maybe I should open an issue on Beam or post on the mailing list? Also the output of the pipeline in my case is saved into HDFS, not the local filesystem. The strange thing is that I see Flink tasks completing successfully, the deadlock occurs between finishing the previous task and launching the next.

**Comment by tvalentyn** [comment] 2019-11-14 17:43
Are you sure you are running `taxi_pipeline_beam` example and not `taxi_pipeline_portable_beam`? If you have made changes to the example, and have these changes somewhere on your fork, please share them too. I can open the issue in Beam once I can reproduce it. Also, I've opened  https://issues.apache.org/jira/browse/BEAM-8651  for another issue I mentioned earlier.

**Comment by tkakantousis** [comment] 2019-11-14 17:49
I'm not using the portable one and I haven't done any changes. Only change is that the input/output files are in HDFShdfs, not local.

**Comment by tvalentyn** [comment] 2019-11-14 17:52
Do you observe the issue when input/output files are local? How about when running the example outside of Jupyter,  using python interpreter directly?

**Comment by tvalentyn** [comment] 2019-11-14 18:42
It appears that that taxi_pipeline_beam uses beam orchestrator on Direct runner, so I am not sure how you end up using Flink if you are running  taxi_pipeline_beam...

**Comment by tkakantousis** [comment] 2019-11-14 20:09
I haven't tried with local files and outside jupyter. I end up using Beam/Flink because I set the `beam_pipeline_args`, similarly to here https://github.com/tensorflow/tfx/blob/0.14.0/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_portable_beam.py#L140

From what I understand these two examples run the same pipeline, except for the Beam vs Airflow DagRunner and the Direct vs Portable runer. So instead of changing AirflowDagRunner to BeamDagRunner in `taxi_pipeline_portable_beam`, I added the beam_pipeline_args` in `taxi_pipeline_beam`. There's also a comment here https://github.com/tensorflow/tfx/blob/0.14.0/tfx/examples/chicago_taxi_pipeline/taxi_pipeline_portable_beam.py#L167 suggesting it is/will be possible to run the PortableRunner with the BeamDAGRunner. 

Am I missing something?

**Comment by tvalentyn** [comment] 2019-11-15 00:00
Thanks, that explains your usecase. As I said, I am just trying to replicate the example on my machine, so it's helpful to know which modifications you did, as I am not intimately familiar with chicago_taxi pipeline. By the way, which tensorflow version are you using?

**Comment by tvalentyn** [comment] 2019-11-15 00:52
Got the example running on  PortableRunner with the BeamDAGRunner, with Flink 1.8.2, TF 1.14.0, Beam 2.16.0,  but was not able to run it on 2.15.0, are you certain you use Beam 2.15.0? 
Also, could you provide the beam_pipeline_args that you set?
Did not repro the error so far.
Looks like it's important to clean up ~/tfx directory before each run, to clean any cached computated results.Otherwise pipelines don't start.

**Comment by tvalentyn** [comment] 2019-11-15 03:01
I can  reproduce this issue on TFX 0.14.0 when increasing parallelism level on Flink Cluster and in  Beam Portable runner as follows:

```
      additional_pipeline_args={                                                
          'beam_pipeline_args': [                                               
              # ----- Beam Args -----.                                          
              '--runner=PortableRunner',                                        
              '--job_endpoint=localhost:8099',                                  
              '--environment_type=LOOPBACK',                                       
              '--sdk_worker_parallelism=12',                                       
              '--experiments=use_loopback_process_worker=True',                 
              '--environment_cache_millis=1000000',                             
              '--parallelism=12',                                                  
              '--experiments=worker_threads=100',                               
              '--experiments=pre_optimize=all',                                    
              '--execution_mode_for_batch=BATCH_FORCED',                        
          ],                                                                    
      }, 
```
Looking further to understand the rootcause.

**Comment by tkakantousis** [comment] 2019-11-15 08:41
Thank you for looking into it, it's great you managed to reproduce. I'm on TensorFlow 1.14.0.
My beam_pipeline_args are same as yours except I'm using `environment_type=PROCESS` and `--parallelism=1`

**Comment by tvalentyn** [comment] 2019-11-16 00:08
No, it does not - it fails 100% of the time. There are at least 5 different failure modes that I've observed:
```
_frozen_importlib._DeadlockError: deadlock detected by _ModuleLock(...)
```
```
ModuleNotFoundError: No module named 'tensorflow.python.util.tf_export.SymbolAlreadyExposedError'; 'tensorflow.python.util.tf_export' is not a package
```
```
tensorflow.python.util.tf_export.SymbolAlreadyExposedError: Symbol BytesList is already exposed as ('train.BytesList',)
```

These happen during unpickling of a payload within Beam code.  On one occasion, the code had to retry 9 times before `pickler.loads()` call finished without an exception. I plan to further investigate this problem in https://issues.apache.org/jira/browse/BEAM-8651 . 

I am also seeing following errors, possibly related:

An error during pickling as opposed to unpickling:
```
... 
 File "/usr/local/google/home/valentyn/tmp/tfx_py37_master/lib/python3.7/site-packages/dill/_dill.py", line 910, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/google/home/valentyn/tmp/tfx_py37_master/lib/python3.7/site-packages/dill/_dill.py", line 1394, in save_function
    obj.__dict__), obj=obj)
  File "/usr/lib/python3.7/pickle.py", line 638, in save_reduce
    save(args)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python3.7/pickle.py", line 789, in save_tuple
    save(element)
  File "/usr/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/google/home/valentyn/tmp/tfx_py37_master/lib/python3.7/site-packages/apache_beam/internal/pickler.py", line 180, in new_save_module_dict
    for m in sys.modules.values():
RuntimeError: dictionary changed size during iteration
 [while running 'Run[Transform]']
```
The workaround for pickling errors can be to retry unpickling (https://github.com/apache/beam/pull/10133).

I am also encontering:
```
packages/apache_beam/runners/worker/bundle_processor.py", line 1149, in _create_pardo_operation
    if not dofn_data[-1]:
TypeError: 'NoneType' object is not subscriptable
 [while running 'Run[Transform]']
```
which may be a different error, filed: https://issues.apache.org/jira/browse/BEAM-8730

**Comment by tvalentyn** [comment] 2019-11-20 21:06
All errors observed here should be fixed with https://github.com/apache/beam/pull/10167. Feel free to patch this PR. We plan to cherrypick this fix into Beam 2.17.0 that is in the works.

**Comment by tvalentyn** [comment] 2019-11-20 22:09
Thanks again, @tkakantousis, for opening this issue.

**Comment by tkakantousis** [comment] 2019-11-21 09:00
Great, looking forward to the next release :) 
Thank you so much @tvalentyn for looking into it.

**Closed** 2019-11-22 13:32 UTC
Labels: stat:awaiting tensorflower, type:bug
